---
title: 'Math 451 HW #4'
author: "Maxwell Levin"
date: "September 14, 2018"
output: pdf_document
---


## Question 1.

#### In the game of dominoes, each piece is marked with three numbers. The pieces are symmetrical so that the pairs in the tuple are not ordered (so, for example, $\small{(2, 2, 6) = (6, 2, 2)}$, but $\small{(2, 6, 2) \neq (2, 2, 6)}$). How many different pieces can be formed using the numbers $\small{1, 2, \dots, n}$?

In the case where the dominoes are simply ordered pairs we have just two cases: a pair (i.e. $\small{(1, 1)}$), or two distinct numbers (i.e. $\small{(1, 2)}$). We see that there are $\small{n}$ distinct ways to create a pair, and that there are $\small{n(n-1)}$ ways to create an ordered pair. Since our pairs are not ordered, we divide this by two. Thus the number of distinct ways to create a 2-domino piece from $\small{n}$ numbers is
\[
  n + \frac{n(n-1)}{2} = \frac{n(n+1)}{2}.
\]

In the case where our dominos are constructed from three numbers we have more cases to consider. The first case is that all three numbers are the same (i.e. $\small{(1, 1, 1)}$). There are simply $\small{n}$ distinct ways to do this. Our second case is that we have a pair of numbers like $\small{(1, 1, 2)}$ or $\small{(2, 1, 1)}$ (Note that these are considered to be the same piece.) The number of ways we can do this is $\small{n(n-1)}$, but to prevent overcounting we divide by 2. Our third case is that we have a set of numbers like $\small{(1, 2, 1)}$. There are simply $\small{n(n-1)}$ ways to do this. Our last case is that we have three distinct numbers (i.e. $\small{(1, 2, 3)}$). In this case we have $\small{n(n-1)(n-2)}$ ways to do this, but we divide this by 2 to prevent overcounting due to symmetry (i.e. $\small{(1, 2, 3)}$ is the same as $\small{(3, 2, 1)}$, but not $\small{(1, 3, 2)}$). The total number of ways to create a 3-domino piece from $\small{n}$ numbers is
\[
  n + \frac{n(n-1)}{2} + n(n-1) + \frac{n(n-1)(n-2)}{2},
\]
\[
  \frac{1}{2}n(n^2 + 1).
\]

## Question 2.

#### If $\small{n}$ balls are placed at random into $\small{n}$ cells, find the probability that exactly one cell remains empty and also find the probability that exactly two cells remain empty. We may assume that $\small{n \geq 3}$.


We first note that the number of ways to distribute $\small{n}$ distinct balls into $\small{n}$ distinct cells is $\small{n^n}$. 

We first consider the case where exactly one cell is to remain empty. There are $\small{\binom{n}{1}}$ ways to pick one cell to remain empty. Since we now have $\small{n-1}$ cells and $\small{n}$ balls, for exactly one cell to remain empty we will have to fill one cell with two balls and the rest with exactly one each. We note that there are $\small{\binom{n}{2}}$ ways to pick two balls to group together. We now treat this grouped ball as a single ball, and distribute the $\small{n-1}$ balls into the $\small{n-1}$ cells. There are $\small{(n-1)!}$ ways to do this. Thus the total number of ways to distribute $\small{n}$ balls into $\small{n}$ cells with exactly one empty cell is
\[
  \binom{n}{1} \binom{n}{2} (n - 1)!.
\]
Thus the probability that this will occur is given by
\[
  \frac{\binom{n}{1} \binom{n}{2} (n - 1)!}{n^n} = \frac{\binom{n}{2}n!}{n^n}.
\]

We now consider the case where exactly two cells are to remain empty. Now we have two main cases. The first case is that we have one cell with 3 balls, 2 cells with 0 balls, and $\small{n-3}$ cells with 1 ball each. We can think about this in a similar way to the last problem, but with some slight modifications. Instead of picking one cell to remain empty, we now pick 2. There are $\small{\binom{n}{2}}$ ways to do this. Now we pick 3 balls to group together instead of two balls. There are $\small{\binom{n}{3}}$ ways to do this. We now put that group set of balls into our remaining pile of balls and distribute our new set of $\small{n-2}$ balls into $\small{n-2}$ cells. There are $\small{(n-2)!}$ ways to do this. Thus there are 
\[
  \binom{n}{2} \binom{n}{3} (n-2)!
\]
ways of doing this.

Our second possible case is that we have 2 cells with 2 balls each instead of just one cell with 3 balls. In this case we have $\small{\binom{n}{2}}$ ways to pick the first group of 2 balls and $\small{\binom{n-2}{2}}$ ways to pick the second group of balls. We still have $\small{\binom{n}{2}}$ ways to pick the empty cells and $\small{(n-2)!}$ ways to distribute the groups of balls into $\small{n-1}$ cells. The number of ways of doing this is
\[
  \binom{n}{2} \binom{n-2}{2} \binom{n}{2} (n-2)!.
\]
Thus the probability of distributing $\small{n}$ balls into $\small{n}$ cells with exactly two empty cells is
\[
  \frac{\binom{n}{2} \binom{n}{3} (n-2)! + \binom{n}{2} \binom{n-2}{2} \binom{n}{2} (n-2)!}{n^n},
\]
\[
  = \frac{n!\left(\binom{n}{3} + \binom{n}{2}\binom{n-2}{2}\right)}{2n^n}.
\]
