---
title: 'Math 451 HW #9'
author: "Maxwell Levin"
date: "October 3, 2018"
output: pdf_document
header-includes:
- \usepackage{placeins}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1.
#### Toss a 0.6-coin four times. Let $\small{W}$ be the random variable denoting the difference between the number of heads and the number of tails.

#### (a) There are $\small{2^4 = 16}$ sample points in the sample space. List all sample points in the event where $\small{\{W = -2\}}$.

Note that $\small{\{W=-2\}}$ occurs only when there are three tails and one head, assuming that $\small{W}$ represents the number of heads minus the number of tails. We note that there are four ways of tossing one head and three tails: (H, T, T, T), (T, H, T, T), (T, T, H, T), (T, T, T, H).

#### (b) Find $\small{Pr\{-2 \leq W \leq 2\}}$.

Note that $\small{W}$ is only less than -2 when $\small{W = -4}$ and that $\small{W}$ is only larger than 2 when $\small{W=4}$. In other words, $\small{\{-2 \leq W \leq 2\}}$ excludes the cases when only heads or only tails are tossed. Thus we can calculate $\small{Pr\{-2 \leq W \leq 2\}}$ by taking
\[
  Pr\{-2 \leq W \leq 2\} = 1 - Pr\{W=-4 \cup W=4\} = 1 - \left(Pr\{W=-4\} + Pr\{W=4\}\right),
\]
\[
  Pr\{-2 \leq W \leq 2\} = 1 - \left( (0.4)^4 + (0.6)^4 \right) = 0.8448.
\]
Note that we substitute 0.4 in for the probability of tossing tails and 0.6 in for the probability for tossing heads because we have a 0.6-coin.

#### (c) Find the p.m.f. $\small{f_W(w)}$ of $\small{W}$.

We do this by creating a table for each case.
\begin{table}[!h]
\centering
\begin{tabular}{|l|l|l|l|l|l|}
\hline
$W = w$ & -4 & -2 & 0 & 2 & 4\\ \hline
$f_W(w)$ & $1(0.4^4)$ & $4(0.4^3\cdot0.6)$ & $6(0.4^2\cdot0.6^2)$ & $4(0.4\cdot0.6^3)$ & $1(0.6^4)$\\ \hline
\end{tabular}
\end{table}

We simplify this to get:
\begin{table}[!h]
\centering
\begin{tabular}{|l|l|l|l|l|l|}
\hline
$W = w$ & -4 & -2 & 0 & 2 & 4\\ \hline
$f_W(w)$ & $0.0256$ & $0.1536$ & $0.3456$ & $0.3456$ & $0.1296$\\ \hline
\end{tabular}
\end{table}

Note that we also manually define $\small{f_W(w) = 0}$ when $\small{W=w}$ is not one of $\small{ \{-4, -2, 0, 2, 4\}}$.

## Question 2.
#### Randomly generate an ordered pair (x,y) inside the triangular region with vertices (0,0), (4,0), and (4,3). Let $\small{X}$ and $\small{Y}$ be the random variables denoting the x-coordinate and the y-coordinate respectively. 

#### (a) Find the p.d.f. $\small{f_X(x)}$ of $\small{X}$.

My LaTeX skills are not yet strong enough to make a plot of our triangle, but we should still note from our setup that the probability density function $\small{f_X(x)}$ is proportional to the height of the triangle. We should also note that when $\small{x}$ is outside of the triangle then the probability of it being picked is 0. We can write
\[
  f_X(x)=\left\{
          \begin{array}{ll}
              k\left(\frac{3}{4}x+3\right), &  \text{if } 0 \leq x \leq 4 ; \\[1mm]
              0, & \text{otherwise,} \\[1mm]
          \end{array} 
          \right.
\]

where $\small{k}$ is some proportionality constant relating the height of our triangle to the probability of our x-coordinate. Because $\small{f_X(x)}$ should be a probability density function, we know that the integral of $\small{f_X(x)}$ from negative infinity to positive infinity should be 1. Also note that since $\small{f_X(x)}$ is 0 everywhere except the interval from 0 to 4, this integral becomes:
\[
  \int_0^4 k\left(\frac{-3}{4}x + 3\right) dx = 1.
\]
We integrate this to get
\[
  \frac{-3k}{8}x^2 + 3kx \Big|_0^4 = 6k.
\]

So $\small{k=1}$ makes $\small{f_X(x)}$ a p.d.f. Thus we have
\[
  f_X(x)=\left\{
          \begin{array}{ll}
              \frac{1}{2} - \frac{1}{8}x, &  \text{if } 0 \leq x \leq 4 ; \\[1mm]
              0, & \text{otherwise.} \\[1mm]
          \end{array} 
          \right.
\]


#### (b) Find $\small{Pr\{1 \leq X \leq 3\}}$.

We can find $\small{Pr\{1 \leq X \leq 3\}}$ by taking the integral of $\small{f_X(x)}$ from 1 to 3:
\[
  \int_1^3 \left(\frac{1}{2} - \frac{1}{8}x\right)dx = \frac{1}{2}x - \frac{1}{4}x^2 \Big|_1^3 = \frac{1}{2}.
\]
Thus we have a 50% chance of picking a point (x,y) where the x-coordinate is between 1 and 3.

#### (c) Find the p.d.f. $\small{f_Y(y)}$ of $\small{Y}$.

Similar to part (a), we note that the probability density function $\small{f_Y(y)}$ is proportional to a measure of the width of the triangle: namely the distance between the y-axis and the diagonal of triangle. Solving for $\small{x}$ in the equation $\small{y = \frac{-3}{4}x + 3}$ yields $\small{x = \frac{-4}{3}(y - 3)}$. We can write:
\[
   f_Y(y)=\left\{
          \begin{array}{ll}
              k\left(\frac{-4}{3}y + 4\right), &  \text{if } 0 \leq y \leq 3 ; \\[1mm]
              0, & \text{otherwise.} \\[1mm]
          \end{array} 
          \right.
\]
We again take the integral of $\small{f_Y(y)}$ from negative to positive infinity, noting that only the region from 0 to 3 is applicable to get
\[
  \int_0^3 \left(4k - \frac{4k}{3}y\right)dy = 1 ,
\]
\[
  4ky-\frac{2k}{3}y^2 \Big|_0^3 = 12k -6k \implies k = \frac{1}{6}.
\]
Thus we have 
\[
  f_Y(y)=\left\{
          \begin{array}{ll}
              \frac{2}{3} - \frac{2}{9}y, &  \text{if } 0 \leq y \leq 3 ; \\[1mm]
              0, & \text{otherwise.} \\[1mm]
          \end{array} 
          \right.
\]
