---
title: 'Math 451 HW #1'
author: "Maxwell Levin"
date: "September 7, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment=NA)
```

## Question 1
Toss a coin seven times. List all sample points of the event "a run of four or more heads". How many are there?

We denote the result of tossing the coin in the form $\small{(d_1, d_2, d_3, d_4, d_5, d_6, d_7)}$, where $\small{d_1}$ represents the results of the first toss, $\small{d_2}$ represents the second toss, and so on. For each $\small{d_i}$ we say that $\small{d_i = 1}$ represents a result of heads and $\small{d_i = 0}$ represents a result of tails. We can then list all the possible ways of getting four or more heads in a row as:

```{python, python.reticulate=FALSE, echo=FALSE}
from math import floor, ceil
from random import choice

coin_tosses = set()

def toss():
   return choice([0, 1])


def run(tosses):
   count = 0
   for i in tosses:
       if i == 1:
           count += 1
       elif i == 0:
           count = 0
       if count >= 4:
           return True
   return False


for _ in range(10000):
   result = (toss(), toss(), toss(), toss(), toss(), toss(), toss())
   if sum(result) >= 4 and run(result):
       coin_tosses.add(result)
coin_tosses = sorted(list(coin_tosses))
# print(len(coin_tosses))
# print(*coin_tosses, sep="\n")
l = coin_tosses
cols = 4
split = [l[i:i + int(len(l) / cols)] for i in range(0, len(l), int(len(l) / cols))]
for row in zip(*split):
   print("".join(str.ljust(str(i), 23) for i in row))
```

Thus we see that there are 20 unique possible outcomes with 4 or more heads in a row.

## Question 2. 
Roll three dice. List all sample points of the event "the maximum is 3". How many are there?

We follow a similar format for our notation here. We let $\small{d_1, d_2, d_3}$ represent the result of rolling three dice. Here each $\small{d_i}$ can take on a value from 1 to 6. Below we list all the possibilities of rolling three die so that the maximum is 3: 
```{python, python.reticulate=FALSE, echo=FALSE}
from math import floor, ceil
from random import choice
dice_rolls = set()

def roll():
   return choice([1, 2, 3, 4, 5, 6])


for _ in range(10000):
   result = (roll(), roll(), roll())
   if max(result) == 3:
       dice_rolls.add(result)
dice_rolls = sorted(list(dice_rolls))
# print(len(dice_rolls))
print(*dice_rolls, sep='\n')
```
We see that there are 19 such outcomes.
