---
title: 'Math 451 HW #14'
author: "Maxwell Levin"
date: "October 21, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1.
#### Let *n* be a positive integer. You flip a *p*-coin *n* times. What is the probability that you will observe an odd number of heads? [Hint: Binomial Theorem]

We note that:
\[
  \text{1 = Pr(Odd number of heads) + Pr(Even number of heads)},
\]
\[
  \text{Pr(Even number of heads) = 1 - Pr(Odd number of heads)}.
\]

And that we can calculate Pr(Even number of heads) - Pr(Odd number of heads) by:
\[
  \sum_{k=0}^n \binom{n}{k}(-p)^k(1-p)^{n-k} = [-p + (1-p)]^n = (1 - 2p)^n.
\]

Thus we have
\[
  \text{Pr(Odd number of heads) = Pr(Even number of heads)} - (1 - 2p)^n,
\]
\[
  \text{Pr(Odd number of heads) = 1 - Pr(Odd number of heads)} - (1 - 2p)^n,
\]
\[
  \text{Pr(Odd number of heads)} = \frac{1 - (1 - 2p)^n}{2}.
\]

Note that if we have a fair coin this probability becomes $\small{\frac{1}{2}}$.
 

## Question 2.
#### Two athletic teams play a best of seven series of games: the first team to win 4 games is declared to be the overall winner. Suppose that one of the teams is stronger than the other and wins each game with a probability of 0.6, independent of the outcomes of the other games.
#### a) Let *X* be the number of games played before the series winner is declared. Find the p.m.f. of *X*, *E(X)*, and *Var(X)*.

We note that each game can be thought of as a **Bernoulli** trial where each trial is independent of the other trials, there is a fixed number of trials, and each trial has the same probability of success. If we let *Y* represent the number of wins team A has in *n* games, where the probability of team A winning is *p*, then we can say that *Y* has the binomial distribution:
\[
  f_Y(y) = \binom{n}{y}p^y(1-p)^{n-y}. 
\]

Note that if we set $\small{y = 3}$, we then have the probability of three wins in *n* games. We'll use this fact shortly. 

Now we go through our cases. It is impossible for the series winner to be declared without having played at least four games, so if $\small{x < 4}$ then $\small{f_X(x) = 0}$. At game four we have two ways that the series could end: the better team (Team 1) could win all four games, or the worse team (Team 2) could win all four games. Thus the probability of the game ending immediately after the fourth game is: 
\[
  \text{Pr(Series over at the fourth game)} = (0.6)^4 + (0.4)^4 = 0.1552
\]
  

For the series to end in the fifth game we require that one team win three times in the first four games and then win the fifth game. In other words, we can take $\small{f_Y(3)}$ with $\small{n = 4}$ and $\small{p = 0.6}$ to get the probability of team 1 winning 3 of the first four games. We can then multiply that probability by 0.6 to get the probability that team 1 wins the fifth game and thus the series. We follow the same process for team 2 and add up the probabilities to get
\[
  \text{Pr(Series over at the fifth game)} = \binom{4}{3}(0.6)^4(0.4) + \binom{4}{3}(0.4)^4(0.6) = 0.2688.
\]

For the sixth game we do a similar thing: out of the first five games a team can win at most three games, so we choose those three and then multiply by the probability of that team winning the next game. Doing so we find that:
\[
  \text{Pr(Series over at the sixth game)} = \binom{5}{3}(0.6)^4(0.4)^2 + \binom{5}{3}(0.4)^4(0.6)^2 = 0.29952.
\]

For the seventh game we have:
\[
  \text{Pr(Series over at the seventh game)} = \binom{6}{3}(0.6)^4(0.4)^3 + \binom{6}{3}(0.4)^4(0.6)^3 = 0.27648.
\]

Put together, this is our p.m.f. $\small{f_X(x)}$ of *X*. We construct it in the table below using decimal values:

\begin{table}[!h]
\centering
\begin{tabular}{|c|c|c|c|c|c|c|}
\hline
$X = x$ & x < 4 & 4 & 5 & 6 & 7 & 7 < x \\ \hline
$f_X(x)$ & $0$ & $0.1552$ & $0.2688$ & $0.29952$ & $0.27648$ & $0$\\ \hline 
\end{tabular}
\end{table}


#### b) Find the conditional probability that the stronger team wins the series given that the stronger team wins the first game.

We can treat this problem as if the stronger team only requires three games to win. We then take the sum of the probabilities of the stronger team winning the series at games four, five, six, and seven to get the probability that the stronger team will win the series. Then for game four the probability the stronger team wins the series is:
\[
  \text{Pr(Team 1 wins the series at the fourth game)} = (0.6)^4 = 0.216.
\]

For the fifth game we pick two games out of the previous *three* for the stronger team to win so that we have the number of ways that Team 1 can have three wins coming up into the fifth game. We then multiply by the probability that Team 1 wins three games and by the probability that Team 1 loses one of their games to get the probability that Team 1 wins the series at the fifth game. This is
\[
  \text{Pr(Series over at the fifth game)} = \binom{3}{2}(0.6)^3(0.4) = 0.2592.
\]

For the sixth game we follow the same process to get:
\[
  \text{Pr(Series over at the sixth game)} = \binom{4}{2}(0.6)^3(0.4)^2 = 0.20736.
\]

For the seventh game we have:
\[
  \text{Pr(Series over at the seventh game)} = \binom{5}{2}(0.6)^3(0.4)^3 = 0.13824.
\]

Adding all of these together we see that the probability of the stronger team winner the series given that the stronger team wins the first game is
\[
  \text{Pr(Team 1 wins the series | Team 1 wins first game)} = 0.8208.
\]

#### c) Find the conditional probability that the stronger team wins the first game given that the stronger team wins the series.

We can restate the problem in part (b) using the definition of conditional probability and substitute our results to find:
\[
  \text{Pr(Team 1 wins Series | Team 1 wins Game 1)} = \frac{ \text{Pr(Team 1 wins Series and Team 1 wins Game 1)}}{\text{Pr(Team 1 wins Game 1)}},
\]
\[
  0.8208 = \frac{ \text{Pr(Team 1 wins Series and Team 1 wins Game 1)}}{0.6},
\]
\[
  \text{Pr(Team 1 wins Series and Team 1 wins Game 1)} = (0.6)(0.8208) = 0.49248.
\]

We also restate the current problem using the definition of conditional probability:
\[
  \text{Pr(Team 1 wins Game 1 | Team 1 wins Series)} = \frac{ \text{Pr(Team 1 wins Game 1 and Team 1 wins Series)}}{\text{Pr(Team 1 wins Series)}},
\]
\[
  \text{Pr(Team 1 wins Game 1 | Team 1 wins Series)} = \frac{0.49248}{\text{Pr(Team 1 wins Series)}}.
\]

We now calculate Pr(Team 1 wins Series):
\[
  \text{Pr(Team 1 wins Series)} = (0.6)^4 + \binom{4}{3}(0.6)^4(0.4) + \binom{5}{3}(0.6)^4(0.4)^2 + \binom{6}{3}(0.6)^4(0.4)^3 = 0.710208.
\]

We then have:
\[
  \text{Pr(Team 1 wins Game 1 | Team 1 wins Series)} = \frac{0.49248}{0.710208} \approx 0.69343.
\]
