---
title: 'Math 451 HW #11'
author: "Maxwell Levin"
date: "October 10, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1.
#### Find the p.d.f. of $\small{Y}$ if $\small{Y = e^X}$ and $\small{X}$ has the following p.d.f.
\[
  f_X(x) = \frac{1}{\sigma^2}xe^{-(x/\sigma)^2/2}, \text{ for } 0 < x < \infty,
\]

#### where $\small{\sigma^2}$ is a positive constant.


We know from class that
\[
  f_Y(y) = f_X(g^{-1}(y)) \Big{|} \frac{d}{dy} g^{-1}(y) \Big{|}.
\]

Note that in our case, $\small{Y = g(x) = e^X}$, so $\small{X = g^{-1}(y) = ln(y)}$ and $\small{\frac{dx}{dy} = \frac{1}{y}}$. We can then use this to get
\[
  f_Y(y) = f_X(ln(y)) \Big{|} \frac{1}{y} \Big{|},
\]
\[
  f_Y(y) = \frac{1}{\sigma^2}ln(y)exp\left(-\frac{1}{2}\left(\frac{ln(y)}{\sigma} \right)^2 \right)\frac{1}{y}.
\]

Note that our range for $\small{y}$ is $\small{1 < y < \infty}$, so this becomes
\[
f_Y(y)=
  \left\{
  \begin{array}{ll}
      \frac{1}{\sigma^2}ln(y)exp\left(-\frac{1}{2}\left(\frac{ln(y)}{\sigma} \right)^2 \right)\frac{1}{y} &  \text{if } 1 < y < \infty ; \\[1mm]
      0 & \text{otherwise.} \\[1mm]
  \end{array} 
  \right.
\]



## Question 2.
#### Suppose $\small{X}$ has the geometric p.d.f. $\small{f_X(x) = \frac{1}{3}\left(\frac{2}{3}\right)^x}$, $\small{x = 0, 1, 2, \dots}$. Determine the probability distribution of $\small{Y = X / (X + 1)}$. Note that here both $\small{X}$ and $\small{Y}$ are discrete random variables. To specify the probability distribution of $\small{Y}$, specify its probability mass function.


We know that $\small{Y = \frac{X}{X+1}}$ with $\small{X \sim f_X(x)}$, where $\small{x = 0, 1, 2, \dots}$. To create a probability mass function for $\small{Y}$, we need to figure out what $\small{Pr\{Y = y\}}$ is. We do this by performing a substitution for $\small{Y}$ and simplifying:
\[
  f_Y(y) = Pr\{Y = y\},
\]
\[
  = Pr\left\{\frac{X}{X+1} = y\right\},
\]
\[
  = Pr\left\{X = \frac{y}{1 - y}\right\}
\]

We use the definition of $\small{f_X(x)}$ to get
\[
  f_Y(y) = \frac{1}{3}\left(\frac{2}{3}\right)^\frac{y}{1 - y}.
\]

Note that this makes sense when $\small{y}$ obeys the relation $\small{Y = \frac{X}{X+1}}$, so $\small{y = 0, \frac{1}{2}, \frac{2}{3}, \frac{3}{4}, \dots}$. Thus we have
\[
f_X(x)=
  \left\{
  \begin{array}{ll}
      \frac{1}{3}\left(\frac{2}{3}\right)^\frac{y}{1 - y} &  \text{if } y = 0, \frac{1}{2}, \frac{2}{3}, \dots ; \\[1mm]
      0 & \text{otherwise.} \\[1mm]
  \end{array} 
  \right.
\]


## Question 3. 
#### Let $\small{X}$ have a p.d.f. $\small{f_X(x) = \frac{2}{9}(x+1)}$, $\small{-1 \leq x \leq 2}$. Find the p.d.f. of $\small{Y = X^2}$. Note that Theorem 2.1.8 is not directly applicable in this problem.

We follow the same process as we did in Question 1. First, we note that $\small{Y = g(x) = X^2}$, $\small{X = \pm \sqrt{Y}}$, and $\small{\frac{dx}{dy} = \pm \frac{1}{2\sqrt{y}}}$. Unlike Question 1, our $\small{g(x)}$ is not one-to-one on our interval from (-1, 2). We have to break up our support into two partitions for $\small{x}$: we let $\small{A_1 = (-1, 0)}$ and $\small{A_2 = (0, 2)}$ so that $\small{g(x)}$ is one-to-one on $\small{A_1}$ and $\small{A_2}$. We now compute $\small{f_Y(y)}$ on $\small{A_1}$ and $\small{A_2}$:
\[
   A_1: f_Y(y) = f_X(-\sqrt{y})\Big{|} -\frac{1}{2\sqrt{y}} \Big{|},
\]
\[
  f_Y(y) = \frac{1}{9\sqrt{y}}(1 - \sqrt{y}).
\]
\[
  A_2: f_Y(y) = f_X(\sqrt{y})\Big{|} \frac{1}{2\sqrt{y}} \Big{|},
\]
\[
  f_Y(y) = \frac{1}{9\sqrt{y}}(1 + \sqrt{y}).
\]

We now note that our overlap in $\small{y}$ occurs when $\small{x \in (-1, 1)}$ and that the overlap is $\small{y \in (0, 1)}$ due to the fact that $\small{Y = X^2}$. Taking this into account we have:
\[
f_Y(y)=
  \left\{
  \begin{array}{lll}
      \frac{1}{9\sqrt{y}} &  \text{if } 0 < y < 1; \\[1mm]
      \frac{1}{9\sqrt{y}}(1 + \sqrt{y}) &  \text{if } 1 < y < 4; \\[1mm]
      0 & \text{otherwise.} \\[1mm]
  \end{array} 
  \right.
\]


