---
title: 'Math 451 HW #15'
author: "Maxwell Levin"
date: "October 31, 2018"
output: pdf_document
header-includes:
  \usepackage{siunitx}
  \sisetup{output-exponent-marker=\ensuremath{\mathrm{e}}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1.
#### Get a *POWERBALL* ticket and read the prize tiers information on the back of the ticket. Let *X* be the prize (in dollars) of a single play.

#### (a) Use a table to represent the p.m.f. of *X*


After looking up the rules for the *POWERBALL* lottery game I found that the game works as follows: pick 5 numbers out of 69 for the "white" balls and pick 1 number out of 26 for the "red" ball. The hosts of the game pick 5 white balls and 1 red ball to be winning. Depending on how the numbers you picked match up you can win one of the following prizes: \$4, \$7, \$100, \$50,000, \$1,000,000, and the Jackpot. 

To win \$4 you need to pick the winning red ball and either 1 or 0 of the winning white balls. The probability that this will occur is:
\[
  Pr\{X = \$4\} = 
  \frac{\binom{5}{0}\binom{64}{5}}{\binom{69}{5}} * \frac{\binom{1}{1}\binom{25}{0}}{\binom{26}{1}} + 
  \frac{\binom{5}{1}\binom{64}{4}}{\binom{69}{5}} * \frac{\binom{1}{1}\binom{25}{0}}{\binom{26}{1}}
  \approx \num{3.697e-2}.
\]

To win \$7 you need to pick 2 of the winning white balls and the winning red ball, or exactly 3 of the winning white balls. The probability that this will occur is:
\[
  Pr\{X = \$7\} = 
  \frac{\binom{5}{2}\binom{64}{3}}{\binom{69}{5}} * \frac{\binom{1}{1}\binom{25}{0}}{\binom{26}{1}} + 
  \frac{\binom{5}{3}\binom{64}{2}}{\binom{69}{5}} * \frac{\binom{1}{0}\binom{25}{1}}{\binom{26}{1}}
  \approx \num{3.151e-3}.
\]

To win \$100 you need to pick 3 of the winning white balls and the winning red ball, or exactly 4 of the winning white balls. The probability that this will occur is:
\[
  Pr\{X = \$100\} = 
  \frac{\binom{5}{3}\binom{64}{2}}{\binom{69}{5}} * \frac{\binom{1}{1}\binom{25}{0}}{\binom{26}{1}} + 
  \frac{\binom{5}{4}\binom{64}{1}}{\binom{69}{5}} * \frac{\binom{1}{0}\binom{25}{1}}{\binom{26}{1}}
  \approx \num{9.637e-5}.
\]

To win \$50,000 you need to pick 4 of the winning white balls and the winning red ball. The probability that this will occur is:
\[
  Pr\{X = \$50,000\} = 
  \frac{\binom{5}{4}\binom{64}{1}}{\binom{69}{5}} * \frac{\binom{1}{1}\binom{25}{0}}{\binom{26}{1}}
  \approx \num{1.095e-6}.
\]

To win \$1,000,000 you need to pick all 5 of the winning white balls. The probability that this will occur is:
\[
  Pr\{X = \$1,000,000\} = 
  \frac{\binom{5}{5}\binom{64}{0}}{\binom{69}{5}} * \frac{\binom{1}{0}\binom{25}{1}}{\binom{26}{1}}
  \approx \num{8.556e-8}.
\]

To win the jackpot you need to pick all 5 of the winning white balls and the winning red ball. The probability that this will occur is:
\[
  Pr\{X = Jackpot\} = 
  \frac{\binom{5}{5}\binom{64}{0}}{\binom{69}{5}} * \frac{\binom{1}{1}\binom{25}{0}}{\binom{26}{1}}
  \approx \num{3.422e-9}.
\]

Finally, you can also not win any prize. This happens when you pick 0 of the winning white and red balls, 1 of the winning white balls, or 2 of the winning white balls. The probability that this will occur is:
\[
  Pr\{X = \$0\} = 
  \frac{\binom{5}{0}\binom{64}{5}}{\binom{69}{5}} * \frac{\binom{1}{0}\binom{25}{1}}{\binom{26}{1}} + 
  \frac{\binom{5}{1}\binom{64}{4}}{\binom{69}{5}} * \frac{\binom{1}{0}\binom{25}{1}}{\binom{26}{1}} +
  \frac{\binom{5}{2}\binom{64}{3}}{\binom{69}{5}} * \frac{\binom{1}{0}\binom{25}{1}}{\binom{26}{1}}
  \approx \num{9.598e-1}.  
\]

We can put all of these probabilities in a table to get our p.m.f.:
\begin{table}[!h]
\centering
\begin{tabular}{|c|c|c|c|c|c|c|c|}
\hline
$X = x$ & x = 0 & x = 4 & x = 7 & x = 100 & x = 50,000 & x = 1,000,000 & x = Jackpot \\ \hline
$f_X(x)$ & $\num{9.598e-1}$ & $\num{3.697e-2}$ & $\num{3.151e-3}$ & $\num{9.637e-5}$ & $\num{1.095e-6}$ & $\num{8.556e-8}$ & $\num{3.422e-9}$\\ \hline 
\end{tabular}
\end{table}


#### (b) How much prize should be awarded for the "jackpot" in order for the game to be "fair," i.e. so that $\small{E[X] = \$2}$? [The cost of a single ticket is $2.]

We calculate the expected value and set it equal to \$2 to solve for the size of the *Jackpot*:
\[
\begin{split}
  E[X] = \$2 = 0(\num{9.598e-1}) + 4(\num{3.697e-2}) + 7(\num{3.151e-3}) + 100(\num{9.637e-5}) \\ + 50,000(\num{1.095e-6}) + 1,000,000(\num{8.556e-8}) + Jackpot(\num{3.422e-9}),
\end{split}
\]
\[
  Jackpot = \frac{2 - (4(\num{3.697e-2}) + 7(\num{3.151e-3}) + 100(\num{9.637e-5}) + 50,000(\num{1.095e-6}) + 1,000,000(\num{8.556e-8}))}{\num{3.422e-9}},
\]
\[
  Jackpot \approx \$490,974,868.
\]

This is quite large. According to the official powerball website the current Jackpot is estimated at \$40 dollars, which is much smaller than the required Jackpot size for the game to be fair. Because of this I don't think that I will be buying a powerball ticket anytime soon.

## Question 2.
#### Suppose we independently generate random real numbers $\small{W_1, W_2, \dots, W_n}$ from the interval (0, 1). Find the smallest *n* that yields a probability greater than 0.95 of generating at least one random number exceeding 0.98. 

#### (a) Solve for *n* using the binomial method.

Let *Y* be the number of observed random numbers greater than 0.98. Because the random numbers are uniformly distributed over (0,1) we can say that $\small{Y \sim Binomial(n, 0.02)}$. We want *n* such that $\small{Pr\{Y \geq 1\} > 0.95}$. We can rewrite this as
\[
  1 - Pr\{Y = 0\} > 0.95,
\]
\[
  1 - \left(\binom{n}{0}(0.02)^0(0.98)^n \right) > 0.95,
\]
\[
  0.05 > (0.98)^n,
\]
\[
  \frac{ln(0.05)}{ln(0.98)} < n,
\]
\[
  n = 149
\]

#### (b) Solve for *n* using the Poisson approximation method.

Let *X* be the number of observed random numbers greater than 0.98. We can then approximate *X* using the Poisson distribution, $\small{Poisson(\lambda\approx0.02n)}$. Like before, we search for $\small{Pr\{X \geq 1\} > 0.95}$, which we can rewrite as:
\[
  1 - Pr\{X = 0\} > 0.95,
\]
\[
  Pr\{X = 0\} < 0.05.
\]

Using the Poisson approximation we write this as
\[
  \frac{(0.02)^0}{0!} e^{-0.02n} < 0.05,
\]
\[
  -0.02n < ln(0.05),
\]
\[
  n > \frac{ln(0.05)}{-0.02},
\]
\[
  n = 150.
\]

This is close to the true value we got with our binomial method, so I'm content with the Poisson method as an approximation.