---
title: 'Math 451 HW #13'
author: "Maxwell Levin"
date: "October 19, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1.
#### Ley *Y* be a geometric random variable with p.m.f.
\[
  Pr\{Y = y\} = f_Y(y) = p(1-p)^{y-1} \text{, } y = 1, 2, 3, \dots
\]

#### We have show that $\small{E(Y) = \mu_Y = \frac{1}{p}}$ and that $\small{Var(Y) = \sigma_Y^2 = \frac{1-p}{p^2}}$.


#### (a) Find the conditional probability $\small{Pr\{Y \text{ is divisible by 4 } | Y \text{ is even}\}}$.

We know that 
\[
  Pr\{Y \text{ is divisible by 4 } | Y \text{ is even}\} = 
  \frac{Pr\{Y \text{ is divisible by 4} \cap Y \text{ is even} \}}{Pr\{Y \text{ is even}\}},
\]

and furthermore that 
\[
  \frac{Pr\{Y \text{ is divisible by 4} \cap Y \text{ is even} \}}{Pr\{Y \text{ is even}\}} = 
  \frac{Pr\{Y \text{ is divisible by 4}\}}{Pr\{Y \text{ is even}\}}.
\]

We now compute $\small{Pr\{Y \text{ is divisible by 4}\}}$:
\[
  Pr\{Y \text{ is divisible by 4}\} = Pr\{Y = 4\} + Pr\{Y = 8\} + Pr\{Y = 12\} + \dots,
\]
\[
  = p(1-p)^{4-1} + p(1-p)^{8-1} + p(1-p)^{12-1} + \dots,
\]
\[
  = p(1-p)^3(1 + (1-p)^4 + (1-p)^8 + \dots),
\]
\[
  = p(1-p)^3\left(\frac{1}{1 - (1-p)^4} \right).
\]

And now we compute $\small{Pr\{Y \text{ is even}\}}$:
\[
  Pr\{Y \text{ is even}\} = Pr\{Y = 2\} + Pr\{Y = 4\} + Pr\{Y = 6\} + \dots,
\]
\[
  = p(1-p)^{2-1} + p(1-p)^{4-1} + p(1-p)^{6-1} + \dots,
\]
\[
  = p(1-p)(1 + (1-p)^2 + (1-p)^4 + \dots),
\]
\[
  = p(1-p)\left(\frac{1}{1 - (1-p)^2} \right).
\]

We can now use these to compute 
\[
  \frac{Pr\{Y \text{ is divisible by 4}\}}{Pr\{Y \text{ is even}\}} =
  \frac{p(1-p)^3\left(\frac{1}{1 - (1-p)^4} \right)}{p(1-p)\left(\frac{1}{1 - (1-p)^2} \right)},
\]
\[
  = \frac{(1-p)^2 (1 - (1-p)^2)}{1 - (1-p)^4}.
\]

#### (b) Compute and express $\small{E(Y(Y-1)(Y-2))}$ in terms of *p*. 

We have 
\[
  E(Y(Y-1)(Y-2)) = \sum_{y=3}^\infty y(y-1)(y-2)p(1-p)^{y-1} = p(1-p)^2 \sum_{y=3}^\infty y(y-1)(y-2)(1-p)^{y-3}.
\]

Our knowledge of geometric series yields the following information: 
\[
  \frac{1}{1-r} = \sum_{y=0}^\infty r^y,
\]
\[
  \frac{d^3}{dr^3}\left[\frac{1}{1-r}\right] = \frac{d^3}{dr^3} \left[\sum_{y=0}^\infty r^y\right],
\]
\[
  \frac{6}{(1-r)^4} = \sum_{y=3}^\infty y(y-1)(y-2)r^{y-3}.
\]

We notice that our ratio *r* is $\small{(1-p)}$ and so we have:
\[
  \frac{6}{(1-(1-p))^4} = \sum_{y=3}^\infty y(y-1)(y-2)(1-p)^{y-3},
\]
\[
  \frac{6}{p^4} = \sum_{y=3}^\infty y(y-1)(y-2)(1-p)^{y-3}.
\]

We then have
\[
  p(1-p)^2 \sum_{y=3}^\infty y(y-1)(y-2)(1-p)^{y-3} = p(1-p)^2 \frac{6}{p^4},
\]
\[
  = \frac{6(1-p)^2}{p^3}.
\]

Thus $\small{E(Y(Y-1)(Y-2)) = \frac{6(1-p)^2}{p^3}}$.

#### (c) Use part (b) to compute the skewness measure $\small{\gamma_1 = E[\frac{(Y-\mu_Y)^3}{\sigma_Y^3}]}$ of *Y*.

Before we begin simplifying, we recall from class that $\small{E(Y) = \mu_Y = \frac{1}{p}}$, $\small{E(Y^2) = \frac{2-p}{p^2}}$, and $\small{Var(Y) = \sigma_Y^2 = \frac{1-p}{p^2}}$.

We now use the linearity property to rewrite $\small{\gamma_1}$ as:
\[
  \gamma_1 = \frac{1}{\sigma_Y^3} E[(Y-\mu_Y)^3],
\]
\[
  = \frac{1}{\sigma_Y^3} E[Y^3 - 3\mu_YY^2 +3\mu_Y^2Y - \mu_Y^3],
\]
\[
  = \frac{1}{\sigma_Y^3} \left( E[Y^3] - 3\mu_YE[Y^2] +3\mu_Y^3 - \mu_Y^3\right),
\]
\[
  = \frac{1}{\sigma_Y^3} \left( E[Y(Y-1)(Y-2) + 3Y^2 - 2Y] - 3\mu_YE[Y^2] +2\mu_Y^3 \right),
\]
\[
  = \frac{1}{\sigma_Y^3} \left( E[Y(Y-1)(Y-2)] + 3E[Y^2] - 2\mu_Y - 3\mu_YE[Y^2] +2\mu_Y^3 \right),.
\]

We can now substitute our results from class and part (b) and simplify:
\[
  = \left(\frac{p^2}{1-p}\right)^\frac{3}{2} \left( \frac{6(1-p)^2}{p^3} + 3\left(1 - \frac{1}{p}\right)\left(\frac{2-p}{p^2}\right) - \frac{2}{p} + \frac{2}{p^3} \right),
\]
\[
   = \left(\frac{1}{1-p}\right)^\frac{3}{2} \left( \frac{6(1-p)^2 + (3p-1)(2-p) + 2 - 2p^2}{p^3} \right),
\]
\[
   = \left(\frac{1}{1-p}\right)^\frac{3}{2} \left( p^2 - 5p + 6 \right),
\]
\[
  \gamma_1 = \frac{(p-2)(p-3)}{(1-p)^\frac{3}{2}}
\]

We've found our skewness measure $\small{\gamma_1}$.


#### (d) Compute and express $\small{E[\frac{1}{Y}]}$ in terms of *p*. [Note: $\small{E[\frac{1}{Y}] \neq \frac{1}{E(Y)}}$]

Our knowledge of geometric series yields the following information: 
\[
  \frac{1}{1-r} = 1 + r + r^2 + r^3 + \dots,
\]
\[
  \int\frac{1}{1-r}dr = \int 1 + r + r^2 + r^3 dr, 
\]
\[
  -log(1-r) = r + \frac{1}{2}r^2 + \frac{1}{3}r^3 + \frac{1}{4}r^4\dots
\]
\[
  -log(1-r) = r\left(1 + \frac{1}{2}r + \frac{1}{3}r^2 + \frac{1}{4}r^3\dots\right).
\]
\[
  \frac{-log(1-r)}{r} = 1 + \frac{1}{2}r + \frac{1}{3}r^2 + \frac{1}{4}r^3\dots.
\]

Now that we've established this background we note that: 
\[
  E\left[\frac{1}{Y}\right] = \sum_{y=1}^\infty \frac{1}{y}p(1-p)^{y-1},
\]
\[
  = p\left(1 + \frac{1}{2}(1-p) + \frac{1}{3}(1-p)^2 + \frac{1}{4}(1-p)^3 + \dots \right).
\]

We note that our ratio here is $\small{(1-p)}$ so this becomes
\[
  E\left[\frac{1}{Y}\right] = p\left(\frac{-log(1-(1-p))}{1-p}\right),
\]
\[
  E\left[\frac{1}{Y}\right] = - \frac{plog(p)}{1-p}.
\]


