---
title: 'Math 451 HW #22'
author: "Maxwell Levin"
date: "November 16, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1.
#### (a) Let $\small\mathbf{X}$ be a ranomd variable recording the value observed from rolling a fair dice. Determine which of $\small\mathbf{E[\sqrt{X}]}$ and $\small\mathbf{\sqrt{E[X]}}$ has a larger value.

Note that our pmf $\small{f_X(x)}$ is given by
\[
  f_X(x) = 
  \left\{
  \begin{array}{ll}
  \frac{1}{6}, & \text{ if } x = 1, 2, 3, 4, 5, 6; \\[1mm]
  0, & \text{ otherwise.} \\[1mm]
  \end{array}
  \right.
\]

To calculate $\small{E[\sqrt{X}]}$ we can take
\[
  E[\sqrt{X}] = \sum_{x=1}^6\sqrt{x}f_X(x),
\]
\[
  = \frac{1}{6}(\sqrt{1} + \sqrt{2} + \dots + \sqrt{6}),
\]
\[
  E[\sqrt{X}] \approx 1.805.
\]

We now calculate $\small{\sqrt{E[X]}}$ by
\[
  \sqrt{E[X]} = \sqrt{\sum_{x=1}^6xf_X(x)},
\]
\[
  = \sqrt{\frac{1}{6}(1 + 2 + \dots + 6)},
\]
\[
  \sqrt{E[X]} \approx 1.871.
\]

Thus we have $\small{\sqrt{E[X]} \geq E[\sqrt{X}]}$.

#### (b) Let $\small\mathbf{X}$ be a positive random variable. Use the Cauchy-Schwarz inequality to prove the inequality found in part (a).

We know from class 29 that the Cauchy-Schwarz inequality is
\[
  (E[AB])^2 \leq E[A^2]E[B^2],
\]

where *A* and *B* are two random variables with finite second moments. Consider the case where $\small{A=1, B=\sqrt{X}}$. We then have
\[
  (E[(1)\sqrt{X}])^2 \leq E[1^2]E[(\sqrt{X})^2],
\]
\[
  (E[\sqrt{X}])^2 \leq E[X],
\]
\[
  E[\sqrt{X}] \leq \sqrt{E[X]}.
\]

This confirms our result in part (a).

## Question 2.
#### (a) Let $\small\mathbf{U}$ be a continuous uniform random variable on the interval (1,3). Determine which of 1/$\small\mathbf{E[U]}$ and $\small\mathbf{E[1/U]}$ has the larger value.

We first note that $\small{f_U(u)}$ is given by
\[
  f_U(u) = 
  \left\{
  \begin{array}{ll}
  \frac{1}{2}, & \text{ if } 1 < u < 3;  \\
  0,  &   \text{ otherwise}. \\
  \end{array}
  \right.
\]

We now calculate $\small{1/E[U]}$ by
\[
  E[U] = \int_1^3\frac{1}{2}udu = \frac{9}{4} - \frac{1}{4} = 2,
\]
\[
  1/E[U] = \frac{1}{2}.
\]

We now calculate $\small{E[1/U]}$ by
\[
  E[1/U] = \int_1^3 \frac{1}{2u}du = \frac{1}{2}ln(3) - \frac{1}{2}ln(1) = \frac{1}{2}ln(3).
\]

Because $\small{\frac{1}{2}ln(3) > \frac{1}{2}}$ we have shown that $\small{E[1/U] > 1/E[U]}$


#### (b) Let $\small\mathbf{U}$ be a positive random variable. Use the Cauchy-Schwarz inequality to prove the inequality found in part (a).

Consider the case where $\small{A = \sqrt{U}}$ and $\small{B = \sqrt{\frac{1}{U}}}$. The Cauchy-Schwarz inequality then yields
\[
  \left(E\left[\sqrt{U}\sqrt{\frac{1}{U}}\right]\right)^2 \leq E[(\sqrt{U})^2]E\left[\left(\sqrt{\frac{1}{U}}\right)^2\right],
\]
\[
  (E[1])^2 \leq E[U]E\left[\frac{1}{U}\right],
\]
\[
  \frac{1}{E[U]} \leq E\left[\frac{1}{U}\right].
\]

This confirms our results in part (a).

## Question 3.
#### A deck consists of 52 cards labeled 1 to 52. You deal 5 cards at random from a well-shuffled deck of 52 cards. Call the five observed numbers $\small\mathbf{X_1, X_2, X_3, X_4, X_5}$.

#### (a) If you deal the 5 cards with replacement, find $\small\mathbf{E[X_1 + X_2 + X_3 + X_4 + X_5]}$ and $\small\mathbf{Var[X_1 + X_2 + X_3 + X_4 + X_5]}$.

Note that the pmf of *X* if *X* is simply the result of one random card from the deck is 
\[
  f_X(x) =
  \left\{
  \begin{array}{ll}
  \frac{1}{52}, & \text{ if } x = 1, 2, \dots, 52; \\
  0,  &   \text{ otherwise.} \\
  \end{array}
  \right.
\]

Note that because expectation values have the linearity property we can write
\[
  E[X_1 + X_2 + X_3 + X_4 + X_5] = E[X_1] + E[X_2] + E[X_3] + E[X_4] + E[X_5].
\]

Also note that each of $\small{X_1, X_2, X_3, X_4, X_5}$ have the pmf defined above, so we can rewrite this as
\[
  E[X_1 + X_2 + X_3 + X_4 + X_5] = 5E[X_1],
\]
\[
  = 5\sum_{x=1}^{52}\frac{1}{52}x,
\]
\[
  = 5\left(\frac{52(52+1)}{2}\frac{1}{52}\right),
\]
\[
  E[X_1 + X_2 + X_3 + X_4 + X_5] = 132.5.
\]

To calculate $\small{Var[X_1 + X_2 + X_3 + X_4 + X_5]}$ we can use the fact that 
\[
  Var[X_1 + X_2 + X_3 + X_4 + X_5] = \sum_{i=1}^5 E[X_i] + \sum_{i=1}^5\sum_{j=1, j\neq i} Cov(X_i, X_j).
\]

Since we are sampling with replacement, we know that each draw is independent of other draws. This means that the covariance of the values of two different draws is 0. Thus our variance is given by
\[
  Var[X_1 + X_2 + X_3 + X_4 + X_5] = \sum_{i=1}^5 E[X_i],
\]
\[
  = 5\left(E[X_i^2] - (E[X_i]^2) \right),
\]
\[
  = 5\left(\sum_{i=1}^{52}\frac{1}{52}x_i^2 - \left(\sum_{i=1}^{52}\frac{1}{52}x_i\right)^2\right),
\]
\[
  = \frac{1}{52}\left(\frac{52(52+1)(2\cdot52-1)}{6}\right) - \left(\frac{1}{52}\left(\frac{52(52+1)}{2}\right)\right)^2,
\]
\[
  Var[X_1 + X_2 + X_3 + X_4 + X_5] = 1126.25.
\]


#### (b) If you deal the 5 cards without replacement, find $\small\mathbf{E[X_1 + X_2 + X_3 + X_4 + X_5]}$ and $\small\mathbf{Var[X_1 + X_2 + X_3 + X_4 + X_5]}$.

Note that our expected value remains the same as in part (a). That is,
\[
  E[X_1 + X_2 + X_3 + X_4 + X_5] = 132.5.
\]

Our variance is a little trickier to calculate because our covariance term is no longer 0. Recall that covariance is given by
\[
  Cov(X_i, X_j) = E[X_iX_j] - E[X_i]E[X_j], 
\]
\[
  = \sum_{i=1}^{52}\sum_{j=1, i\neq j}^{52} \frac{X_iX_j}{52\cdot51} - (E[X_i])^2.
\]

To plug this into Wolfram Alpha we have to slightly modify how we write this:
\[
   Cov(X_i, X_j) = \sum_{i=1}^{52}\sum_{j=1}^{52} \frac{X_iX_j}{52\cdot51} - \sum_{i=1}^{52}\frac{X_i^2}{52\cdot51} - (E[X_i])^2,
\]
\[
  = -\frac{53}{12}.
\]

Thus our variance is given by
\[
  Var[X_1 + X_2 + X_3 + X_4 + X_5] = \sum_{i=1}^5Var(X_i) + \sum_{i=1}^{5}\sum_{j=1, i\neq j}^{5}Cov(X_i, X_j),
\]
\[
  = 5Var(X_i) + 20Cov(X_i, X_j),
\]
\[
  Var[X_1 + X_2 + X_3 + X_4 + X_5] \approx 1038.17.
\]


