---
title: 'Math 451 HW #21'
author: "Maxwell Levin"
date: "November 14, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1.
#### You roll three fair dice. Let $\small\mathbf{X}$ be the minimum and let $\small\mathbf{Y}$ be the median. 

#### (a) Use a two-way table to show the joint pmf of $\small\mathbf{X}$ and $\small\mathbf{Y}$.

We construct the following table:

\begin{table}[!h]
\centering
\begin{tabular}{|c|c|c|c|c|c|c|c|}
\hline
$ $ & $ X = 1$ & $X = 2$ & $X = 3$ & $X = 4$ & $X = 5$ & $X = 6$\\ \hline
$Y = 1$ & $16/6^3$ & $0$ & $0$ & $0$ & $0$ & $0$\\ \hline
$Y = 2$ & $27/6^3$ & $13/6^3$ & $0$ & $0$ & $0$ & $0$\\ \hline
$Y = 3$ & $21/6^3$ & $21/6^3$ & $10/6^3$ & $0$ & $0$ & $0$\\ \hline
$Y = 4$ & $15/6^3$ & $15/6^3$ & $15/6^3$ & $7/6^3$ & $0$ & $0$\\ \hline
$Y = 5$ & $9/6^3$ & $9/6^3$ & $9/6^3$ & $9/6^3$ & $4/6^3$ & $0$\\ \hline
$Y = 6$ & $3/6^3$ & $3/6^3$ & $3/6^3$ & $3/6^3$ & $3/6^3$ & $1/6^3$\\ \hline
\end{tabular}
\end{table}

#### (b) Find $\small\mathbf{Pr\{X + Y \leq 4\}}$.

To find this probability we can take $\small{\sum f_{X,Y}(x, y)}$ over all $\small{(x, y)}$ such that $\small{x + y \leq 4}$. Doing so we see that
\[
  Pr\{X+Y \leq 4\} = \frac{16}{6^3} + \frac{27}{6^3} + \frac{13}{6^3} + \frac{21}{6^3} = \frac{77}{216} \approx 0.356.
\]


#### (c) Find the marginal pmf of $\small\mathbf{X}$, $\small\mathbf{E[X]}$, and $\small\mathbf{Var[X]}$.

We can calculate the marginal pmf of $\small{X}$ by taking the sum of all the values in the columns for $\small{X=1, X=2, \dots, X=6}$. Doing so we see that 
\[
  f_X(x) = 
  \left\{
  \begin{array}{ll}
     91/6^3, &  \text{if } x = 1; \\[1mm]
     61/6^3, &  \text{if } x = 2; \\[1mm]
     37/6^3, &  \text{if } x = 3; \\[1mm]
     19/6^3, &  \text{if } x = 4; \\[1mm]
     7/6^3, &  \text{if } x = 5; \\[1mm]
     1/6^3, &  \text{if } x = 6; \\[1mm]
      0, & \text{otherwise.} \\[1mm]
  \end{array} 
  \right.
\]

We can calculate $\small{E[X]}$ by taking the sum $\small{\sum_1^6 xf_X(x)}$. Doing so we see that
\[
  E[X] = 1\left(\frac{91}{6^3}\right) + 2\left(\frac{61}{6^3}\right) + 3\left(\frac{37}{6^3}\right) +
          4\left(\frac{19}{6^3}\right) + 5\left(\frac{7}{6^3}\right) + 6\left(\frac{1}{6^3}\right),
\]
\[
  E[X] = \frac{441}{216} = \frac{49}{24} \approx 2.042.
\]

We now calculate $\small{Var[X] = E[X^2] + E[X]^2}$ by first taking
\[
  E[X^2] = 
  1^2\left(\frac{91}{6^3}\right) + 2^2\left(\frac{61}{6^3}\right) + 3^2\left(\frac{37}{6^3}\right) +
  4^3\left(\frac{19}{6^3}\right) + 5^3\left(\frac{7}{6^3}\right) + 6^3\left(\frac{1}{6^3}\right),
\]
\[
  E[X^2] = \frac{1183}{216} \approx 5.477.
\]

We can now calculate $\small{Var[X]}$ by 
\[
  Var[X] = \frac{1183}{216} - \left(\frac{49}{24}\right)^2 \approx 1.308.
\]

#### (d) Find the marginal pmf of $\small\mathbf{Y}$, $\small\mathbf{E[Y]}$, and $\small\mathbf{Var[Y]}$.

We can calculate the marginal pmf of $\small{Y}$ by taking the sum of all the values in the rows for $\small{Y=1, Y=2, \dots, Y=6}$. Doing so we see that 
\[
  f_Y(y) = 
  \left\{
  \begin{array}{ll}
     16/6^3, &  \text{if } y = 1; \\[1mm]
     40/6^3, &  \text{if } y = 2; \\[1mm]
     52/6^3, &  \text{if } y = 3; \\[1mm]
     52/6^3, &  \text{if } y = 4; \\[1mm]
     40/6^3, &  \text{if } y = 5; \\[1mm]
     16/6^3, &  \text{if } y = 6; \\[1mm]
      0, & \text{otherwise.} \\[1mm]
  \end{array} 
  \right.
\]

We can calculate $\small{E[Y]}$ by taking the sum $\small{\sum_1^6 yf_Y(y)}$. Doing so we see that
\[
  E[Y] = 1\left(\frac{16}{6^3}\right) + 2\left(\frac{40}{6^3}\right) + 3\left(\frac{52}{6^3}\right) +
          4\left(\frac{52}{6^3}\right) + 5\left(\frac{40}{6^3}\right) + 6\left(\frac{16}{6^3}\right),
\]
\[
  E[Y] = \frac{756}{216} = \frac{7}{2} = 3.5.
\]

We now calculate $\small{E[Y^2]}$ by first taking
\[
  E[Y^2] = 
  1^2\left(\frac{16}{6^3}\right) + 2^2\left(\frac{40}{6^3}\right) + 3^2\left(\frac{52}{6^3}\right) +
  4^3\left(\frac{52}{6^3}\right) + 5^3\left(\frac{40}{6^3}\right) + 6^3\left(\frac{16}{6^3}\right),
\]
\[
  E[Y^2] = \frac{3052}{216} = \frac{763}{54} \approx 5.477.
\]

We can now calculate $\small{Var[Y]}$ by 
\[
  Var[Y] = E[Y^2] - E[Y]^2 = \frac{763}{54} - 3.5^2 \approx 1.879.
\]

#### (e) Find the conditional pmf of $\small\mathbf{Y}$ given $\small\mathbf{X=x}$, $\small\mathbf{x=1,2,3,4,5,6}$.

Note that the conditional pmf of $\small{Y}$ given $\small{X=x}$ is given by the following expression
\[
  f_{y|X}(y|X=x) = \frac{f_{X,Y}(x,y)}{f_X(x)}.
\]

So then we would have
\[
  f_{y|X}(y|X=1) = \frac{f_{X,Y}(1,y)}{f_X(1)},
\]
\[
  f_{y|X}(y|X=2) = \frac{f_{X,Y}(2,y)}{f_X(2)},
\]
\[
  \vdots
\]
\[
  f_{y|X}(y|X=6) = \frac{f_{X,Y}(6,y)}{f_X(6)},
\]

as our pmf's of $\small{Y}$ given $\small{X}$. This would take up a lot of space to write out by hand, so what we can instead do is write up our results in a matrix, where each column represents the distribution of $\small{Y}$ given $\small{X=x}$ for $\small{x = 1, 2, \dots, 6}$. We do this below:

\begin{table}[!h]
\centering
\begin{tabular}{|c|c|c|c|c|c|c|c|}
\hline
$ $ & $f_{y|X}(y|X=1)$ & $f_{y|X}(y|X=2)$ & $f_{y|X}(y|X=3)$ & $f_{y|X}(y|X=4)$ & $f_{y|X}(y|X=5)$ & $f_{y|X}(y|X=6)$\\ \hline
$Y = 1$ & $16/91$ & $0$ & $0$ & $0$ & $0$ & $0$\\ \hline
$Y = 2$ & $27/91$ & $13/61$ & $0$ & $0$ & $0$ & $0$\\ \hline
$Y = 3$ & $21/91$ & $21/61$ & $10/37$ & $0$ & $0$ & $0$\\ \hline
$Y = 4$ & $15/91$ & $15/61$ & $15/37$ & $7/19$ & $0$ & $0$\\ \hline
$Y = 5$ & $9/91$ & $9/61$ & $9/37$ & $9/19$ & $4/7$ & $0$\\ \hline
$Y = 6$ & $3/91$ & $3/61$ & $3/37$ & $3/19$ & $3/7$ & $1$\\ \hline
\end{tabular}
\end{table}



#### (f) Are $\small\mathbf{X}$ and $\small\mathbf{Y}$ independent? Justify your answer.

No. There are plenty of cases where $\small{f_{x,Y}(x,y) \neq f_X(x)f_Y(y)}$. Consider one such example where $\small{X=2, Y=1}$. In this case we have
\[
  f_{X,Y}(2, 1) = 0,
\]
\[
  f_X(2)f_Y(1) = \left(\frac{61}{6^3}\right)\left(\frac{16}{6^3}\right),
\]

which are clearly not equal. Thus *x* and *Y* are not independent.

#### (g) Find the correlation coefficient, $\small\mathbf{\rho(X, Y)}$.

Recall that we calculate $\small{\rho(X,Y)}$ by 
\[
  \rho(x, Y) = \frac{Cov(X,Y)}{\sigma_x\sigma_y},
\]

and that 
\[
  Cov(X,Y) = E[XY] - \mu_x\mu_y.
\]

To calculate $\small{E[XY]}$ we can calculate
\[
  E[XY] = \sum_{x=1}^6 \sum_{y=1}^6 xy f_{X,Y}(x,y),
\]

which we can calculate by using our table in part (a). Doing so we find that
\[
  E[XY] = \frac{1756}{216} = \frac{439}{54} \approx 8.130,
\]
\[
  Cov(X,Y) = \frac{439}{54} - \left(\frac{49}{24}\right)\left(\frac{7}{2}\right) \approx 0.984,
\]
\[
  \rho(X,Y) = \frac{Cov(X,Y)}{\sqrt{Var[X]Var[Y]}} \approx 0.627.
\]
