---
title: 'Math 451 HW #6'
author: "Maxwell Levin"
date: "September 19, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment=NA)
```

## Question 1.

#### Verify the following identities for $\small{n \geq 2}$.

#### a) $\small{\sum_{k=0}^n (-1)^k \binom{n}{k} = 0}$.

Recall that for some $\small{x, y \in \mathbb{R}}$ we have
\[
  \sum_{k=0}^n \binom{n}{k}x^ky^{n-k} = (x + y)^n.
\]
Consider $\small{x=-1, y=1}$. In this case we have
\[
  \sum_{k=0}^n \binom{n}{k}(-1)^k (1)^{n-k} = (-1 + 1)^n,
\]
\[
  \sum_{k=0}^n (-1)^k \binom{n}{k} = 0.
\]



#### b) $\small{\sum_{k=1}^n k \binom{n}{k} = n2^{n-1}}$.

Take 
\[
  \frac{d}{dx} \sum_{k=0}^n \binom{n}{k} x^k y^{n-k} = 
  \sum_{k=1}^n k \binom{n}{k} x^{k-1} y^{n-k}.
\]
and
\[
  \frac{d}{dx} (x + y)^n = n(x+y)^{n-1}.
\]
Because we know that 
\[
  \sum_{k=0}^n \binom{n}{k}x^ky^{n-k} = (x + y)^n,
\]
we also know that the derivatives of each side with respect to $\small{x}$ are also equal, i.e.
\[
  \sum_{k=1}^n k \binom{n}{k} x^{k-1} y^{n-k} = 
    n(x+y)^{n-1}.
\]
Consider $\small{x=1, y=1}$. We then have 
\[
  \sum_{k=1}^n k \binom{n}{k} (1)^{k-1} (1)^{n-k} =
  n(1 + 1)^{n-1},
\]
\[
  \sum_{k=1}^n k \binom{n}{k} =
  n2^{n-1},
\]


#### c) $\small{\sum_{k=1}^n (-1)^{k+1} k \binom{n}{k} = 0}$.

Recall from (b) that 
\[
  \sum_{k=1}^n k \binom{n}{k} x^{k-1} y^{n-k} = 
    n(x+y)^{n-1}.
\]
Consider $\small{x=-1, y=1}$. We then have
\[
  \sum_{k=1}^n k \binom{n}{k} (-1)^{k-1} (1)^{n-k} = 
    n(-1 + 1)^{n-1},
\]
\[
  \sum_{k=1}^n k \binom{n}{k} (-1)^{k-1} = 
    0.
\]
Since $\small{(-1)^{k-1} = (-1)^{k+1}}$ we then see our identity holds:
\[
  \sum_{k=1}^n k \binom{n}{k} (-1)^{k+1} = 
    0.
\]



## Question 2. 

## For $\small{n \geq 1}$, guess a formula for the following sum, and prove your guess.
\[
  \binom{n}{0}^2 + \binom{n}{1}^2 + \binom{n}{2}^2 + \dots + \binom{n}{n}^2.
\]

Consider $\small{ (x + 1)^{2n} }$. We know from Theorem 1 on class notes 5 that
\[
  (x + 1)^{2n} = \sum_{k = 0}^{2n} \binom{2n}{k}x^k.
\]

We also know that
\[
  ((x + 1)^n)^2 = (x + 1)^{2n},
\]

and thus that 
\[
  \left(\sum_{k=0}^n \binom{n}{k}x^k\right)^2 = \sum_{k = 0}^{2n} \binom{2n}{k}x^k.
\]

We can expand this to see that 
\[
  \left(\binom{n}{0}x^0 + \binom{n}{1}x^1 + \dots + \binom{n}{n}x^n\right)^2 = 
  \binom{2n}{0}x^0 + \binom{2n}{1}x^1 + \dots + \binom{2n}{n}x^2 + \dots + \binom{2n}{2n}x^{2n}.
\]

Note that because the two sides are equal it must be true that the $\small{x^n}$ terms on both sides are equal to one another. Thus we have
\[
  \left(\binom{n}{0}\binom{n}{n} + \binom{n}{1}\binom{n}{n-1} + \dots + \binom{n}{n}\binom{n}{0}\right)x^n = 
  \binom{2n}{n}x^n.
\]
We can rearrange this to get:
\[
  \binom{n}{0}^2 + \binom{n}{1}^2 + \binom{n}{2}^2 +  \dots + \binom{n}{n}^2 = \binom{2n}{n}.
\]












