---
title: 'Math 451 HW #3'
author: "Maxwell Levin"
date: "September 12, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment=NA)
```

## Question 1.

#### If $\small{P(A) = \frac{1}{3}}$ and $\small{P(B^c) = \frac{1}{4}}$, can $\small{A}$ and $\small{B}$ be disjoint?

We assume that $\small{P(\cdot)}$ is a probability set function on some set $\small{\mathbb{S}}$ and that $\small{A}$ and $\small{B}$ are subsets of $\small{\mathbb{S}}$. Since we are given $\small{P(B^c) = \frac{1}{4}}$ we can say that
\[
  P(B^c \cup (B^c)^c) = P(\mathbb{S}) = 1,
\]
\[
  P(B^c \cup B) = 1.
\]

Since $\small{B}$ and $\small{B^c}$ are disjoint by definition this reduces to:
\[
  P(B^c) + P(B) = 1,
\]
\[
  P(B) = 1 - P(B^c) = 1 - \frac{1}{4} = \frac{3}{4}.
\]

Suppose now that $\small{A}$ and $\small{B}$ are disjoint. Since $\small{P(\cdot)}$ is a probability set function we know that 
\[
  P(A \cup B) = P(A) + P(B).
\]
That is, 
\[
  P(A \cup B) = \frac{1}{3} + \frac{3}{4} = \frac{13}{12} > 1.
\]
This is impossible! The largest probability permitted is 1. Thus $\small{A}$ and $\small{B}$ are not disjoint. 


## Question 2.

#### Let $\small{\mathbb{N}}$. denote the set of natural numbers. For each natural number, $\small{n}$, let $\small{\mathbb{N}_n = \{1, 2, \dots, n\}}$. If $\small{A}$ is a subset of $\small{\mathbb{N}}$ with its cardinality denoted by $\small{|A|}$, and the limit
\[
  D(A) = \lim_{n \to \infty} \frac{|A \cap \mathbb{N}_n|}{n}
\]

#### exists, then $\small{D(A)}$ is called the density of $\small{A}$. Is $\small{D(\cdot}$ a probability set function? 


To check if $\small{D(\cdot)}$ is a probability set function, we need to check for non-negativity, normalization, and countable additivity. We first check non-negativity. Since the cardinality of any set is always greater than or equal to zero, we see that our negativity condition is satisfied. We now check our normality condition. Consider 
\[
  D(\mathbb{N}) = \lim_{n \to \infty} \frac{|\mathbb{N} \cap \mathbb{N}_n|}{n} = 1.
\]
Thus $\small{D(\cdot)}$ satisfies the normality condition. We now check the countable additivity property. Let $\small{A_1, A_2, \dots}$ be a set of mutually exclusive events in $\small{\mathbb{N}}$. Consider
\[
  \small{D(\cup_{i=1}^\infty A_i)} = \lim_{n \to \infty} \frac{|\cup_{i=1}^\infty A_i \cap \mathbb{N}_n|}{n},
\]
\[
  = \frac{|\cup_{i=1}^\infty A_i \cap \mathbb{N}|}{|\mathbb{N}|},
\]
\[
  = \frac{|\cup_{i=1}^\infty A_i|}{|\mathbb{N}|},
\]
\[
  = \frac{|A_i| + |A_2| + \dots|}{|\mathbb{N}|},
\]
\[
  = \sum_{i=1}^\infty \frac{|A_i|}{|\mathbb{N}|},
\]
\[
  = \sum_{i=1}^\infty D(A_i).
\]

Thus we see that $\small{D(\cdot)}$ satisfies the countable additivity condition. Since $\small{D(\cdot)}$ is non-negative, normalized, and satisfies the countable additivity condition, we can say that $\small{D(\cdot)}$ is a probability set function on $\small{\mathcal{P}(\mathbb{N})}$.




