---
title: 'Math 451 HW #8'
author: "Maxwell Levin"
date: "September 22, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1.
#### There are 47 people, $\small{P_1, P_2, \dots, P_{47}}$ in a room. Let $\small{A_{i, j}}$ denote the event that person $\small{P_i}$ and person $\small{P_j}$ have the same birthday.

#### a) Are events $\small{A_{1, 2}}$ and $\small{A_{3, 4}}$ independent? Please justify your answer.

Yes they are independent. If we knew that person 1 and person 2 shared a birthday, then we would not learn anything about the birthday's of people 3 and 4. In other words,
\[
  Pr(A_{3, 4} | A_{1, 2}) = Pr(A_{3, 4}) = \frac{1}{365}.
\]



#### b) Are events $\small{A_{1, 2}}$ and $\small{A_{1, 3}}$ independent? Please justify your answer.


Yes, they are independent. We note that the probability of $\small{A_{1, 2}}$ and $\small{A_{1, 3}}$ both occuring is the same as the probability of $\small{A_{1, 2}}$ occuring multiplied by the probability of $\small{A_{1, 3}}$ occuring. In other words, the probability that person 1 shares a birthday with person 2 and with person 3 is the same as the probability that person 1 shares a birthday with person 2 multiplied by the probability that person 1 share a birthday with person 3. More formally, this is 
\[
  Pr(A_{1, 2} \cap A_{1, 3}) = Pr(A_{1, 2})Pr(A_{1, 3}) = \frac{1}{365} \cdot \frac{1}{365}
\]


#### c) Are events $\small{A_{1, 2}}$, $\small{A_{1, 3}}$ and $\small{A_{2, 3}}$ independent? Please justify your answer.


No, they are not independent. To justify this, we assume the opposite: that the events $\small{A_{1, 2}}$, $\small{A_{1, 3}}$ and $\small{A_{2, 3}}$are independent. Because they are independent, we can write

\[
  Pr(A_{1, 2} \cap A_{1, 3} \cap A_{2, 3}) = Pr(A_{1, 2} \cap A_{1, 3})Pr(A_{2, 3}) = Pr(A_{1, 2}) Pr(A_{1, 3})Pr(A_{2, 3}).
\]
This becomes 
\[
  \left(\frac{1}{365} \right)^3.
\]

Additionally, the multiplication rule tells us that 
\[
  Pr(A_{1, 2} \cap A_{1, 3} \cap A_{2, 3}) = Pr(A_{1, 2}) Pr(A_{1, 3} | A_{1, 2}) Pr(A_{2, 3} |A_{1, 2} \cap A_{1, 3}).
\]

We can draw on (a) and (b) to reduce this to:
\[
  \frac{1}{365} \cdot \frac{1}{365} \cdot Pr(A_{2, 3} |A_{1, 2} \cap A_{1, 3}).
\]

We can further solve this by noting that $\small{A_{1, 2} \cap A_{1, 3}}$ implies that person 2 and person 3 share a birthday. This means that 
\[
 Pr(A_{2, 3} |A_{1, 2} \cap A_{1, 3}) = 1,
\]

i.e.
\[
  Pr(A_{1, 2}) Pr(A_{1, 3} | A_{1, 2}) Pr(A_{2, 3} |A_{1, 2} \cap A_{1, 3}) = \left(\frac{1}{365} \right)^2.
\]

Since 
\[
  \left(\frac{1}{365} \right)^2 \neq \left(\frac{1}{365} \right)^3, 
\]
we have a contradiction. Thus $\small{A_{1, 2}}$, $\small{A_{1, 3}}$ and $\small{A_{2, 3}}$ are not independent.




## Question 2.
#### Alice and Bob watch as Curtis repeatedly throws a pair of dice. Alice wins if a sum of 7 comes up but not a difference of 3. Bob wins if a difference of 3 comes up but not a sum of 7. If Curtis rolls (2, 5) or (5, 2), the game is over and no one wins. Otherwise, the game continues until Alice of Bob wins or Curtis rolls (2, 5) or (5, 2). Consider the following events:
\[
  A = \text{"Alice wins"}
\]
\[
  B = \text{"Bob wins"}
\]
\[
  E = \text{"The game ends on the second throw"}
\]

#### a) Compute $\small{Pr(A), Pr(B), \text{ and } Pr(E)}$.

First note that there are 36 possible options for rolling two six-sided die. The pairs (1, 6), (2, 4), (4, 2), and (6, 1) all result in a win for Alice, the pairs (1, 4), (3, 6), (6, 3), and (4, 1) all result in a win for Bob, (2, 5), and (5, 2) result in a loss for everyone, and the remaining 26 possible options result in another throw. This pattern continues after each throw until the game ends. 

Thus we see that Alice has a $\small{\frac{4}{36}}$ chance of winning on the first throw, a $\small{\frac{4}{36}\left(\frac{26}{36}\right)}$ chance of winning on the next throw, a $\small{\frac{4}{36}\left(\frac{26}{36}\right)^2}$ on the following throw, and so on. We can write this as:
\[
  \frac{4}{36} + \frac{4}{36}\left(\frac{26}{36}\right) + \frac{4}{36}\left(\frac{26}{36}\right)^2 + \frac{4}{36}\left(\frac{26}{36}\right)^3 + \dots,
\]
\[
  = \frac{4}{36}\left(1 +  \frac{26}{36} + \left(\frac{26}{36}\right)^2 + \left(\frac{26}{36}\right)^3 + \dots \right),
\]
\[
  = \frac{4}{36} \cdot \frac{1}{1 - \frac{26}{36}} = \frac{4}{36}\cdot\frac{36}{10} = \frac{2}{5}.
\]
Thus $\small{Pr(A) = \frac{2}{5}}$


Since Bob has the same probability of winning on each turn as Alice does, we know that $\small{Pr(B) = \frac{2}{5}}$.

To calculate $\small{Pr(E)}$, we note that there are 26 ways of reaching the second roll, and then 4 + 4 + 2 ways of having it end that turn. Thus
\[
  Pr(E) = \frac{26}{36}\left(\frac{4}{36} + \frac{4}{36} + \frac{2}{36}\right) = \frac{26}{36}\cdot\frac{10}{36}.
\]
(We do not simplify this fully to make our lives easier in part (b))


#### b) Are the events $\small{A}$ and $\small{E}$ independent? Please justify your answer.


Yes, $\small{A}$ and $\small{E}$ are independent. We can show this by proving that $\small{Pr(A \cap E) = Pr(A)Pr(E)}$. Note that $\small{Pr(A \cap E)}$ represents the event that Alice wins on the second throw. The probability of reaching the second throw is $\small{\frac{26}{36}}$ and the probability that Alice will win on any given throw is $\small{\frac{4}{36}}$, so 
\[
  Pr(A \cap E) = \frac{26}{36}\cdot\frac{4}{36}
\]
Also note that $\small{Pr(A)Pr(E)}$ is 
\[
  \left(\frac{4}{36}\cdot\frac{36}{10}\right)\cdot\left(\frac{26}{36}\cdot\frac{10}{36}\right) = \frac{26}{36}\cdot\frac{4}{36}.
\]
Thus we have $\small{Pr(A \cap E) = Pr(A)Pr(E)}$, so $\small{A}$ and $\small{E}$ are independent.




