---
title: 'Math 451 HW #2'
author: "Maxwell Levin"
date: "September 10, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment=NA)
```

## Question 1

####Let $\small{ \{A_\alpha : \alpha \in \Gamma\}}$ be a collection of sets. Prove that 
\[
  (\cap_\alpha A_\alpha)^c = \cup_\alpha A_\alpha^c.
\]

Let $\small{s \in (\cap_\alpha A_\alpha)^c}$ for all $\small{\alpha \in \Gamma}$ be arbitrary. We then have
\[
  s \in (\cap_\alpha A_\alpha)^c \iff s \notin \cap_\alpha A_\alpha \text{ for some } \alpha \in \Gamma
\]
by definition of the compliment of a set. From there we see that 
\[
  s \notin \cap_\alpha A_\alpha \text{ for some } \alpha \in \Gamma \iff s \notin A_\alpha \text{ for some } \alpha \in \Gamma,
\]
\[
  s \notin A_\alpha \text{ for some } \alpha \in \Gamma \iff s \in A_\alpha^c \text{ for some } \alpha \in \Gamma,
\]
\[
  s \in A_\alpha^c \text{ for some } \alpha \in \Gamma \iff s \in \cup_\alpha A_\alpha^c.
\]
Thus we have shown that $\small{(\cap_\alpha A_\alpha)^c \subseteq \cup_\alpha A_\alpha^c}$ and $\small{\cup_\alpha A_\alpha^c \subseteq (\cap_\alpha A_\alpha)^c}$, i.e. that $\small{ (\cap_\alpha A_\alpha)^c = \cup_\alpha A_\alpha^c}$.


## Question 2.

####Let $\small{S = \{1, 2, 3, 4, 5\}}$ be the sample space. What is the smallest Borel field consisting of both $\small{\{1, 2\}}$ and $\small{\{3\}}$? (This is called the Borel field generated by events $\small{\{1, 2\}}$ and $\small{\{3\}}$.)

The smallest Borel field that we can construct with these generators is the following set:

\[
  \mathbb{\beta} = \{ \emptyset, S, \{1, 2\}, \{ 3, 4, 5\}, \{ 3\}, \{1, 2, 4, 5\}, \{1, 2, 3\}, \{4, 5\} \}.
\]


## Question 3.

####Let $\small{S = \mathbb{Z}^+}$ be the set of positive integers. Define $\small{\mathcal{F}}$ to be the collection of all subsets $\small{A_i}$ of $\small{S}$ such that either $\small{A_i}$ is finite or $\small{A_i^c}$ is finite. Is $\small{\mathcal{F}}$ a Borel field?

No. We see that the empty set is an element of $\small{\mathcal{F}}$, and that $\small{\mathcal{F}}$ is closed under complementation almost trivially, but we lack closure of countable unions:

Consider $\small{A_1 = \{ 2\}, A_2 = \{4\}, A_3 = \{6\}, \dots}$. Each $\small{A_i}$ is a finite subset of $\small{S = \mathbb{Z}^+}$, so they are all elements of $\small{\mathcal{F}}$. Note that the union of all $\small{A_i}$ is the (countably infinite) set of positive even integers. Additionally, note that the compliment of the set of all positive even integers is the set of all positive odd integers. Because both of these sets are infinite, we see that neither is an element of $\small{\mathcal{F}}$. Therefore $\small{\mathcal{F}}$ is not closed under countable unions.





