---
title: 'Math 451 HW #23'
author: "Maxwell Levin"
date: "November 19, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1.

#### There are *n* sets of twins, attending a party. Each twin wears and identical hat to his or her twin sibling, and there are *n* different kinds of hats. Each person hands their hat to a hat clerk. When the part ends, the hat clerk returns the hats completely at random. Let *X* be the number of people with their own hats back. Find $\small\mathbf{E[X]}$ and $\small\mathbf{Var[X]}$.

We can calculate $\small{E[X]}$ using a sum of indicators $\small{X_1, X_2, \dots, X_{2n}}$, where 
\[
  X_i = 
  \left\{
  \begin{array}{ll}
  1, & \text{ if the ith person gets their hat back}; \\
  0, & \text{ otherwise.} \\
  \end{array}
  \right.
\]

We caculate the expected value by:
\[
  E[X] = E[X_1 + X_2 + \dots + X_{2n}],
\]
\[
  = \frac{2}{2n}(1) + \frac{2}{2n}(1) + \dots + \frac{2}{2n}(1),
\]
\[
  E[X] = 2.
\]

We now calculate the variance of *X* by 
\[
  Var[X] = \sum_{i=1}^{2n} Var(X_i) + \sum_{i=1}^{2n}\sum_{j=1, i\neq j}^{2n} Cov(X_i, X_j).
\]

Where we can calculate $\small{Var(X_i)}$ by:
\[
  Var(X_i) = E[X_i^2]-E[X_i]^2,
\]
\[
  = \left(\frac{1}{n}(1)^2 + \left(1-\frac{1}{n}\right)(0)^2 \right) - \left(\frac{1}{n}(1) + \left(1-\frac{1}{n}\right)(0) \right)^2,
\]
\[
  Var[X_i] = \frac{1}{n} - \frac{1}{n^2}.
\]

We now calculate the covariance in two parts to account for the possibility of two partygoers being twins. If persons *i* and *j* are twins then $\small{Cov(X_i, X_j)}$ is given by:
\[
  Cov(X_i, X_j) = E[X_iX_j] - E[X_i]E[X_j],
\]
\[
  = \frac{2}{2n}\frac{1}{2n-1} - \frac{1}{n}\frac{1}{n},
\]
\[
  = \frac{1}{n}\left(\frac{1}{2n-1}-\frac{1}{n} \right).
\]

Note that there are $\small{2n}$ twins total, so there are $\small{2n}$ twin terms in the covariance double sum. Since there are $\small{(2n)^2}$ terms total there are $\small{(2n)^2-2n-2n = 2n(2n-2)}$ non-twin terms in the covariance double sum, each of which looks like:
\[
  Cov(X_i, X_j) = \frac{2}{2n}\frac{2}{2n-1} - \frac{1}{n}\frac{1}{n},
\]
\[
  = \frac{1}{n}\left(\frac{2}{2n-1}-\frac{1}{n}\right).
\]

We now calculate the variance by
\[
  Var(X) = 2n\left(\frac{1}{n} - \frac{1}{n^2}\right) + 2n\left(\frac{1}{n}\left(\frac{1}{2n-1} - \frac{1}{n}\right)\right) + 2n(2n-2)\left(\frac{1}{n}\left(\frac{2}{2n-1} - \frac{1}{n}\right)\right),
\]
\[
  = 2\left(1 - \frac{1}{n}\right) + 2\left(\frac{1}{2n-1}- \frac{1}{n}\right) + 2(2n-2)\left(\frac{2}{2n-1} - \frac{1}{n}\right),
\]
\[
  2\left(1 - \frac{1}{n} + \frac{1}{2n-1} - \frac{1}{n} + \frac{4n}{2n-1} - 2 - \frac{4}{2n-1} + \frac{2}{n}\right),
\]
\[
  2\left(\frac{4n-3}{2n-1} - 1\right),
\]
\[
  = 4\left(\frac{n-1}{2n-1}\right).
\]