---
title: 'Math 451 HW #20'
author: "Maxwell Levin"
date: "November 12, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1.

#### Let *X* and *Y* be the life spans (in hours) of two electronic devices, and their joint p.d.f. is given below.
\[
  f_{X, Y}(x,y) =
  \left\{
  \begin{array}{ll}
     ce^{-x -2y}, &  \text{if } 0 < x < y < \infty; \\[1mm]
      0, & \text{otherwise.} \\[1mm]
  \end{array} 
  \right.
\]


#### (a) Determine the value of $\small\mathbf{c}$ .
We can use the fact that
\[
  \int_{all X,Y}f_{X, Y}(x, y)dxdy = 1
\]

to calculate $\small{c}$:
\[
  \int_{0 < x < y < \infty} ce^{-x -2y} dxdy = \int_0^\infty \int_0^y ce^{-x}e^{-2y} dxdy,
\]
\[
   = \int_0^\infty ce^{-2y}\left(-e^{-x}\right)\Big{|}_0^y dy,
\]
\[
  = c\int_0^\infty \left(e^{-2y} - e^{-3y}\right)dy,
\]
\[
  = c \left(-\frac{1}{2}e^{-2y} + \frac{1}{3}e^{-3y}  \right)\Big{|}_0^\infty,
\]
\[
  = \left(\frac{1}{2} - \frac{1}{3}\right)c.
\]

Thus we have
\[
  \frac{1}{6}c = 1,
\]
\[
  c = 6.
\]

#### (b) Find $\small\mathbf{Pr\{X + Y \leq 4\}}$.
We can find this by taking the integral
\[
  \int 6e^{-x-2y}dxdy
\]

over the set of $\small{(x,y) \text{ such that } x+y\leq 4}$. We can encode this condition into our bounds of integration as follows:
\[
  \int_0^2\int_x^{4-x} 6e^{-x-2y}dydx,
\]
\[
  = \int_0^2 6e^{-x}\left(-\frac{1}{2}e^{-2y} \right)\Big{|}_x^{4-x} dx,
\]
\[
  = \int_0^2 6e^{-x}\left(-\frac{1}{2}e^{-8+2x} - \left(-\frac{1}{2}e^{-2x}\right) \right)dx,
\]
\[
  = 3\int_0^2e^{-3x} - e^{x-8}dx,
\]
\[
  = 3\left(-\frac{1}{3}e^{-3x} - e^{x-8} \right)\Big{|}_0^2,
\]
\[
  = (-e^{-6} - 3e^{-6}) - (-e^0 - 3e^{-8}),
\]
\[
  = 1 + \frac{3}{e^8} - \frac{4}{e^6} \approx 0.991
\]

Thus the probability that $\small{Pr\{X + Y \leq 4\}}$ is about 0.991.


#### (c) Find the marginal p.d.f. of $\small\mathbf{X}$, and calculate $\small\mathbf{E(X)}$ and $\small\mathbf{Var(X)}$.

We can find the marginal p.d.f. of $\small{X}$ by integrating out $\small{y}$:
\[
  f_X(x) = \int_x^\infty 6e^{-x}e^{-2y}dy,
\]
\[
  = 6e^{-x}\left(-\frac{1}{2}e^{-2y} \right)\Big{|}_x^\infty,
\]
\[
  = 3e^{-3x}.
\]

Note that this only makes sense when $\small{x > 0}$. If $\small{x < 0}$ then the p.d.f. is 0.

We calculate the expected value by
\[
  E[X] = \int_{-\infty}^\infty xf_X(x)dx = \int_0^\infty 3xe^{-3x}dx,
\]
\[
  = \left(3x\left(-\frac{1}{3}e^{-3x}\right)\right)\Big{|}_0^\infty
  - \int_0^\infty \left(- \frac{1}{3}e^{-3x}\left(3\right)\right)dx,
\]
\[
  = 0 + \left(-\frac{1}{3}e^{-3x}  \right)\Big{|}_0^\infty,
\]
\[
  = \frac{1}{3}.
\]

To calculate the variance we use the fact that 
\[
  Var[X] = E[X^2] - E[X]^2.
\]

We calculate $\small{E[X^2]}$ by
\[
  E[X^2] = \int_{-\infty}^\infty x^2f_X(x)dx = \int_0^\infty 3x^2e^{-3x}dx,
\]
\[
  = \left(-x^2e^{-3x} \right)\Big{|}_0^\infty - \int_0^\infty (-2xe^{-3x})dx,
\]
\[
  =  \int_0^\infty (2xe^{-3x})dx,
\]
\[
  = \left(-\frac{2}{3}e^{-3x}\right)\Big{|}_0^\infty - \int_0^\infty \left(-\frac{2}{3}e^{-3x}  \right)dx
\]
\[
  = \frac{2}{3}\int_0^\infty e^{-3x}dx,
\]
\[
  = -\frac{2}{9}e^{-3x}\Big{|}_0^\infty,
\]
\[
  = \frac{2}{9}.
\]

Thus the variance is:
\[
  Var[X] = \frac{2}{9} - \left(\frac{1}{3}\right)^2 = \frac{1}{9}.
\]

#### (d) Find the marginal p.d.f. of $\small\mathbf{Y}$, and calculate $\small\mathbf{E(Y)}$ and $\small\mathbf{Var(Y)}$.

We can find the marginal p.d.f. of $\small{Y}$ by integrating out $\small{x}$:
\[
  f_Y(y) = \int_0^y 6e^{-2y}e^{-x}dx,
\]
\[
  = 6e^{-2y}\left(-e^{-x} \right)\Big{|}_0^y,
\]
\[
  =  6e^{-2y}\left(1 - e^{-y} \right).
\]

Note that this only makes sense when $\small{y > 0}$. If $\small{y < 0}$ then the p.d.f. is 0.

We calculate the expected value by
\[
  E[Y] = \int_{-\infty}^\infty yf_Y(y)dy = \int_0^\infty 6e^{-2y}\left(1 - e^{-y} \right)ydy.
\]

We could integrate this manually by using integration by parts as we did in part (c), but I am running short on time so I will use Wolfram alpha to evaluate this integral instead. By integrating we see that 
\[
  E[Y] = \frac{5}{6}.
\]

To calculate the variance we take:
\[
  Var[Y] = E[Y^2] - E[Y]^2.
\]

To get $\small{E[Y^2]}$ we need to evaluate the integral
\[
  E[Y^2] = \int_{-\infty}^\infty y^2f_Y(y)dy = \int_0^\infty 6e^{-2y}\left(1 - e^{-y} \right)y^2dy.
\]

To save time, we also use Wolfram Alpha as opposed to length integration by parts by hand. Doing so we see that
\[
  E[Y^2] = \frac{19}{18}.
\]

Thus the variance is given by
\[
  Var[Y] = \frac{19}{18} - \left(\frac{5}{6}\right)^2 = \frac{13}{36}.
\]


#### (e) Are $\small\mathbf{X}$ and $\small\mathbf{Y}$ independent? Justify your answer.

No. Recall that two random variables that are jointly distributed are called independent if
\[
  f_{X,Y}(x,y) = f_X(x)f_Y(y).
\]

For us we have
\[
  f_{X,Y}(x,y) = 6e^{-x-2y},
\]

and 
\[
  f_X(x)f_Y(y) = (3e^{-3x})(6e^{-2y}(1 - e^{-y})),
\]
\[
  = 18e^{-3x-2y} - 18e^{-3x-3y},
\]

where $\small{0 < x < y < \infty}$. Since $\small{f_{X,Y}(x,y) \neq f_X(x)f_Y(y)}$ we can say that $\small{X}$ and $\small{Y}$ are not independent. 

#### (f) Find $\small\mathbf{Cov(X, Y)}$.

We know from class notes 28 that we can calculate the covariance by
\[
  Cov(X,Y) = E[XY] - \mu_x \mu_y.
\]

We calculate $\small{E[XY]}$ below:
\[
  E[XY] = \int_0^\infty\int_0^y 6xye^{-x-2y}dxdy.
\]

This is another case where we could solve this using integration by parts, but due to my own time constraints I will evaluate the integral in Wolfram Alpha. Doing so we see that
\[
  E[XY] = \frac{7}{18}.
\]

Thus the covariance is given by
\[
  Cov(X,Y) = \frac{7}{18} - \left(\frac{1}{3} \right)\left(\frac{5}{6} \right),
\]
\[
  Cov(X, Y) = \frac{1}{9}.
\]

Since the covariance is greater than 0 we can say that $\small{X}$ and $\small{Y}$ are positively correlated.



#### (g) Find $\small\mathbf{\rho(X, Y)}$

Recall from class notes 28 that we can calculate the correlation coefficient $\small{\rho(X,Y)}$ by
\[
  \rho(X,Y) = \frac{Cov(X,Y)}{\sigma_x \sigma_y}.
\]

We can use our result from (f) to get
\[
  \rho(X,Y) = \frac{1/9}{\sqrt{1/9}\sqrt{13/36}} = \frac{2}{\sqrt{13}}.
\]


#### (h) Find the conditional p.d.f. of $\small\mathbf{Y}$ given $\small\mathbf{X= x, \forall x > 0}$

We know from class (Class notes 27) that 
\[
  f_{Y|X} (y|X=x) = Pr\{Y=y | X=x\} = \frac{f_{X,Y}(x,y)}{f_X(x)}.
\]

For us this becomes
\[
  f_{Y|X}(y|X=x) = \frac{6e^{-x-2y}}{3e^{-3x}} = 2e^{2x-2y}.
\]

Note that this only makes sense when $\small{0 < x < y < \infty}$. Otherwise the conditional probability density function of $\small{Y}$ given $\small{X}$ is 0.
