---
title: 'Math 451 Test #1'
author: "Maxwell Levin"
date: "September 28, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem 1 (10 points)
#### Let $\small{S = \{1, 2, 3, 4, 5\}}$ be the sample space. Find the smallest borel field $\small{\mathcal{B}}$ generated by $\small{\{1, 2\}}$ and $\small{\{1, 3\}}$. Also report the number of events in $\small{\mathcal{B}}$.

The smallest borel field of $\small{S}$ generated by $\small{\{1, 2\}}$ and $\small{\{1, 3\}}$ is:
\[
  \mathcal{B} = \{ \emptyset, S, \{1\}, \{2\}, \{3\}, \{1, 2\}, \{1, 3\}, \{2, 3\}, \{4, 5\}, \{1, 2, 3\}, \{1,4, 5\}, \{2, 4, 5\}, \{3, 4, 5\}, \{1, 2, 4, 5\}, \{1, 3, 4, 5\}, \{2, 3, 4, 5\}\}
\]
We notice that $\small{\mathcal{B}}$ has 16 elements.

## Problem 2 (14 points)
#### A rectangular tile consists of 4 squares in a row. Each square is marked with a number from the set $\small{\{1, 2, \dots, n\}, n \geq 1}$. The tile marked with (3, 5, 2, 1) is regarded as the same as the tile marked with (1, 2, 5, 3). But note that the tile marked with (3, 5, 2, 1) is different from the tile marked with (3, 2, 5, 1).
#### (a) (8 points) How many different tiles can be formed?

We consider four main types of tiles: tiles with four distinct numbers, tiles with three distinct numbers, tiles with two distinct numbers, and finally tiles with one distinct number. 

We notice that in our first case there are $\small{\binom{n}{4}}$ ways to pick the four distinct numbers from our collection of $\small{n}$ distinct numbers. Recall from our lessons on permutations that there are $\small{4!}$ different permutations/arrangements of four distinct numbers. Because of the symmetries of our tiles, the number of valid permutations of our four distinct numbers is actually $\small{\frac{1}{2}(4!) = 12}$. This means that there are $\small{12\binom{n}{4}}$ distinct tiles we can create from four distinct numbers.

We have $\small{\binom{n}{3}}$ ways to pick three distinct numbers to use on our tile. There are $\small{\binom{3}{1}}$ ways of picking one of our three distinct numbers to duplicate so that we have four numbers to use on our tile. I am not sure how to use combinatorics to count the number of ways to do this, so I'll perform this manually. Assume, for illustration purposes, that we have drawn the following numbers: 1, 1, 2, 3. Here is a list of configurations of the numbers on the tile to create distinct tiles: (1, 1, 2, 3), (1, 1, 3, 2), (2, 1, 1, 3), (1, 2, 3, 1), (1, 2, 1, 3), (1, 3, 1, 2). We see that there are six distinct ways to do this. Thus the number of distinct tiles we can create with three distinct numbers is $\small{(6)\binom{3}{1}\binom{n}{3} = 18\binom{n}{3}}$.

We have $\small{\binom{n}{2}}$ ways of picking two numbers to use for our tiles in the next case. For illustration purposes say that the two distinct numbers we've chosen are 1 and 2. We can then create the following distinct tiles: (1, 1, 2, 2), (1, 2, 1, 2), (1, 2, 2, 1), (2, 1, 1, 2), (1, 1, 1, 2), (1, 1, 2, 1), (2, 2, 2, 1), (2, 2, 1, 2). There are eight possible distinct tiles possible here. Thus there are $\small{8\binom{n}{2}}$ ways of creating distinct tiles from two distinct numbers. 

In our last case we simply have $\small{n}$ possible choices for our one distinct number and one possible arrangement given that distinct number.

The total number of tiles we can create is the sum of the number of ways we can create tiles for each possible case:
\[
  = 12 \binom{n}{4} + 18\binom{n}{3} + 8 \binom{n}{2} + n.
\]



#### (b) (6 points) For $\small{n \geq 4}$, if a tile is selected at random, what is the probability of selecting a tile marked with four numbers that are nondecreasing or nonincreasing when we read the four numbers from left to right?


A tile is not nondecreasing and not nonincreasing if there is some sequence of numbers in the tile that are increasing then decreasing or decreasing then increasing. For example, tiles such as (1, 2, 1, 3) and (4, 3, 1, 2) are neither nondecreasing nor are they nonincreasing. Thus we do not count such tiles in this problem. As in part (a), we consider four cases.

In our first case we pick four distinct numbers. There are simply $\small{\binom{n}{4}}$ ways of doing this. There is only one way to pick up a tile with four distinct numbers that satisfies our conditions. To illustrate this, say we pick the numbers 1, 2, 3, and 4. We can only arrange these tiles as (1, 2, 3, 4) or (4, 3, 2, 1) so that it satisfies our conditions, but these are the same tile. Thus the number of ways to create tiles with our new conditions from four distinct tiles is $\small{\binom{n}{4}}$. 


The number of ways to pick three distinct numbers is $\small{\binom{n}{3}}$. Within this we must select one of these numbers to duplicate. We have $\small{\binom{3}{1} = 3}$ ways of doing this. For illustration say that the numbers we've selected are 1, 1, 2, and 3. Then we have just one way to arrange these numbers to create a valid tile: (1, 1, 2, 3). Note that separating the ones in any way leads to a tile that we no longer count: (1, 2, 1, 3) and (1, 2, 3, 1) are both neither nonincreasing nor nondecreasing. Thus the number of tiles we can create from three distinct numbers is $\small{3\binom{n}{3}}$. 

We have $\small{\binom{n}{2}}$ ways of picking two distinct numbers. Say we pick 1 and 2. We then can create the tiles (1, 1, 1, 2), (1, 1, 2, 2), and (1, 2, 2, 2). Thus the number of ways of creating tiles from two distinct numbers is $\small{3\binom{n}{2}}$.

The number of ways we can create tiles with one distinct number is simply $\small{n}$.

Thus the total number of tiles we can create with our new conditions is 
\[
  \binom{n}{4} + 3\binom{n}{3} + 3\binom{n}{2} + n.
\]

This means that the probability of drawing a tile that is nondecreasing or nonincreasing is
\[
  \frac{\binom{n}{4} + 3\binom{n}{3} + 3\binom{n}{2} + n}{12 \binom{n}{4} + 18\binom{n}{3} + 8 \binom{n}{2} + n}
\]


## Problem 3 (10 points)
#### There are $\small{n}$ persons, $\small{P_1, P_2, \dots, P_n}$ in a room. Each person is asked for their birthday in order, with the instruction that as soon as a person hears their name they raise their hand. Find the probability that a hand is first raised when the kth person is asked for their birthday (Assume that there are 365 days in a year, and that each day is equally likely to be a birthday for any given person).

To help us get started on this problem we state several properties about the nature of this problem. 

First, we note that $\small{P_1, P_2, \dots P_{k-1}}$ must have birthdays on $\small{k-1}$ days that no one else in the room was born on. As a result, it must be the case that $\small{P_k, P_{k+1}, \dots P_n}$ were born on any of the remaining $\small{365 - (k - 1)}$ days. There are $\small{\binom{365}{k-1}}$ ways we can pick the $\small{k-1}$ distinct days that the first $\small{k-1}$ people were born on. Note that with $\small{k-1}$ people, there are $\small{365^{k-1}}$ total ways that their birthdays could occur. Thus the probability that we will pick their birthdays in this manner is 
\[
  \frac{\binom{365}{k-1}}{365^{k-1}}.
\]

Secondly, we note that $\small{P_k}$ must share a birthday with at least one of $\small{P_{k+1}, P_{k+2} \dots P_n}$. The number of ways that $\small{P_{k+1}}$ will share a birthday with one other person in $\small{P_{k+1}, P_{k+2} \dots P_n}$ is 
\[
  \binom{365 - (k-1)}{1} \binom{n - (k+1)}{1} = (365 - (k - 1))(n - (k +1)).
\]
The number of ways the remaining $\small{n - (k+2)}$ people could have birthdays on days that don't align with the first $\small{k-1}$ people is
\[
  (365 - (k-1))^{n-(k+2)},
\]
so the total number of ways this can occur the way we want it is 
\[
  (365 - (k - 1))(n - (k +1))(365 - (k-1))^{n-(k+2)} = (n - (k +1))(365 - (k-1))^{n-(k+1)}.
\]
The total number of ways these people can be born is 
\[
  365^{n - (k+2)},
\]

So the probability that this event occurs is 
\[
  \frac{(n - (k +1))(365 - (k-1))^{n-(k+1)}}{365^{n - (k+2)}}.
\]

Since we've designed our two probabilities to be independent, the probability that the first goes up when the kth person announces their birthday should be 
\[
  \frac{\binom{365}{k-1}}{365^{k-1}} \cdot \frac{(n - (k +1))(365 - (k-1))^{n-(k+1)}}{365^{n - (k+2)}}.
\]

However, we note that if we run a monte carlo simulation for this problem and compare our approximation to the formula we've just derived for some values of n and k, we find that our formula is not consistent with the Monte Carlo approximation, and that we actually are underestimating the probability that the first hand is raised when the kth person presents their birthday. See below for a trial run of my code:
```{python, python.reticulate=FALSE, comment=NA}
from scipy.misc import comb as ncr
from random import randint

num_runs = 100000

# Here we set n to 20 and k to 10
num_peep = 20
k = 10


def form_guess(n, k):
	"""My formula, as derived in the steps above."""
	prod = ncr(365, k - 1) / (365 ** (k - 1))
	prod *= (n - (k + 1)) * (365 - (k - 1)) ** (n - (k + 1))
	prod /= 365 ** (n - (k + 2))
	return prod


def share_birthday(p, people):
	"""Returns True if someone other than person p has the
	   same birthday as person p, False otherwise"""
	if people[p] in people[0:p] or people[p] in people[p + 1:-1]:
		return True


def single_run(people):
	"""Does a single run through the first k people. If the
	   first hand is raised at the kth person, return 1. 
	   Otherwise return 0."""
	for i in range(k):
		if share_birthday(i, people):
			return 0
	if share_birthday(k, people):
		return 1
	return 0


# This runs the trial many times.
prb = 0
for i in range(num_runs):
	# Assign people random birthdays
	people = [randint(1, 365) for _ in range(num_peep)]
	prb += single_run(people) / num_runs
print("Formula 1: ", form_guess(num_peep, k))
print("Monte Carlo: ", prb)

```



## Problem 4 (16 points)
#### Alice tosses a coin that lands heads with probability $\small{p_a}$, and Bob tosses a coin that lands heads with probability $\small{p_b}$. They toss their coins simultaneously over and over again until someone gets the first head to be the winner of a brand new car. If they get their first heads at the same time, then it is a draw and nobody wins the car. Let $\small{A}$ be the event that Alice wins the brand new car, $\small{D}$ be the event that the game ends in a draw, and $\small{E}$ be the event that the game ends of the second toss. 

#### (a) (6 points) Find $\small{Pr(A \cup D)}$.

Since Alice winning and a draw occuring cannot possibly happen at the same time, we can say that  $\small{A}$ and $\small{D}$ are two mutually exclusive events. Because of this we know that
\[
  Pr(A \cup D) = Pr(A) + Pr(D).
\]

We begin by calculating $\small{Pr(A)}$. Since Alice has a probability of getting heads of $\small{p_a}$ she has a probability of getting tails of $\small{1 - p_a}$. Note that for any given toss Bob has a probability of getting tails of $\small{1 - p_b}$. Since Alice wins if she gets a head while Bob gets tails, Alice wins with a probability of $\small{p_a(1- p_b)}$ on any given toss. To advance to another toss both Alice and Bob have to get tails. Advancing to another toss occurs with probability $\small{(1 - p_a)(1- p_b)}$. Thus the probability that Alice wins is given by
\[
  Pr(A) = p_a(1 - p_b) + p_a(1 - p_a)(1 - p_b)^2 + p_a(1- p_a)^2(1 - p_b)^3 + \dots,
\]
\[
  = p_a(1-p_b)(1 + (1-p_a)(1-p_b) + (1-p_a)^2(1-p_b)^2 + \dots),
\]
\[
  Pr(A) = \frac{p_a(1-p_b)}{1 - (1-p_a)(1 - p_b)} = \frac{p_a(1-p_b)}{p_a + p_b - p_ap_b}.
\]

We now calculate the probability of a draw. This occurs when both Alice and Bob get heads on the same toss. Note that in order for the game to not end before they both get heads on the same toss, neither can win, i.e. Alice and Bob must toss tails until they BOTH toss heads at the same time. The probability Alice and Bob both get heads on any given toss is $\small{p_ap_b}$, and the probability they both get tails on any given toss is $\small{(1-p_a)(1-p_b)}$. Thus the probability the game ends in a draw is
\[
  Pr(D) = p_ap_b + p_ap_b(1-p_a)(1-p_b) + p_ap_b(1-p_a)^2(1-p_b)^2 + \dots,
\]
\[
  = p_ap_b(1 + (1-p_a)(1-p_b) + (1-p_a)^2(1-p_b)^2 + \dots),
\]
\[
  P(D) = \frac{p_ap_b}{1 - (1-p_a)(1-p_b)} = \frac{p_ap_b}{p_a + p_b - p_ap_b}.
\]

Thus the probability that the game ends in a draw or Alice wins is
\[
  P(A) + Pr(D) = \frac{p_a(1-p_b)}{p_a + p_b - p_ap_b} + \frac{p_ap_b}{p_a + p_b - p_ap_b},
\]
\[
  Pr(A \cup D) = \frac{p_a(1-p_b) + p_ap_b}{p_a + p_b - p_ap_b} = \frac{p_a}{p_a + p_b - p_ap_b}.
\]

#### (b) (5 points) Find $\small{Pr(E)}$.

Note that the probability that the game will not end on the first turn is $\small{(1-p_a)(1-p_b)}$. Also note that the game can end on a given turn if Alice wins, Bob wins, or they draw. Ony any given turn, Alice wins with probability $\small{p_a(1-p_b)}$, Bob wins with probability $\small{p_b(1-p_a)}$, and the game ends in a draw with probability $\small{p_ap_b}$. Thus the probability that the game ends on the second turn is
\[
  Pr(E) = (1-p_a)(1-p_b)(p_a(1-p_b) + p_b(1-p_a) + p_ap_b),
\]
\[
  Pr(E) = (1-p_a)(1-p_b)(p_a + p_b - p_ap_b).
\]



#### (c) (5 points) Are events $\small{A}$ and $\small{E}$ independent? Please justify your answer.

Yes, events $\small{A}$ and $\small{E}$ are independent. We can verify this by checking that 
\[
  Pr(A \cap E) = Pr(A)Pr(E).
\]

Note that $\small{Pr(A \cap E)}$ denotes the probability that Alice wins on the second turn. We can use our results from part (b) to show that 
\[
  Pr(A \cap E) = (1-p_a)(1-p_b)(p_a(1-p_b)) = p_a(1-p_a)(1-p_b)^2.
\]

We can also use our results from (a) and (b) to show that 
\[
  Pr(A)Pr(E) = \frac{p_a(1-p_b)}{p_a + p_b - p_ap_b} \cdot (1-p_a)(1-p_b)(p_a + p_b - p_ap_b),
\]
\[
  Pr(A \cap E) = Pr(A)Pr(E) = p_a(1-p_a)(1-p_b)^2.
\]
Thus events $\small{A}$ and $\small{E}$ are independent.