---
title: 'Math 490 HW #11'
author: "Maxwell Levin"
date: "February 28, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment=NA, fig.width = 6, fig.height = 6, fig.align = "center")
```

## Question 1.

#### a. Show the work of finding $\small{\sigma_\phi}$ discussed in Example 1 of this class.




#### b. Show the work of finding the c.d.f. $\small{G(\cdot)}$ and the inverse $\small{G^{-1}(\cdot)}$ discussed in Example 1 of this class.





## Question 2.

#### a. If sample size $\small{N = 100}$, what is the mean and the standard deviation of the importancesampling estimator $\small{Z_{100}^{IS}}$ discussed in Example 1 of this class?



#### b. With sample size $\small{N = 100}$, use R to simulate 1024 importance sampling estimates of $\small{I}$. Make a histogram of those 1024 importance sampling estimates, and report the mean and the standard deviation of those 1024 estimates.



#### c. If sample sizw $\small{N = 100}$, how likely is the importance sampling estimator $\small{Z_{100}^{IS}}$ to yield an estimate of $\small{I}$ within error $\small{\pm0.01}$? Use R to simulate this probability with 10000 runs.



#### d. How large should $\small{N}$ be such that the importance sampling estimator $\small{Z_{100}^{IC}}$ would yield an estimate of $\small{I}$ within error $\small{\pm0.01}$ with probability $\small{95\%}$?
